import icons from '@/app/coins/icons.json';
import type coins from '@/app/coins/coins.json';

type Coin = (typeof coins)[number];
type Params = { provider?: string; sort?: string; state?: string; q?: string };
const base = 'https://www.agencypad.fun';
const providers = [
  ['','All minds','4828'],['anthropic','Anthropic','3570'],['openai','OpenAI','649'],['x-ai','xAI','420'],['google','Google','57'],['mistralai','Mistral','50'],['deepseek','DeepSeek','33'],['qwen','Qwen','25'],['moonshotai','Moonshot','11'],['minimax','MiniMax','7'],['z-ai','Z.ai','6'],
];
function Icon({ name }: { name: string }) { const svg = (icons as Record<string,string>)[name]; return svg ? <span className="agency-icon" dangerouslySetInnerHTML={{ __html: svg }} /> : <span className="agency-icon">∗</span>; }
export function AgencyHeader() { return <header className="agency-nav"><div className="agency-wrap agency-nav-row"><a className="agency-logo" href={base}>AGENCY</a><nav className="agency-nav-links" aria-label="Main"><a href={`${base}/unbound`}>Agents</a><a className="on" href="/coins">Coins</a><a href={`${base}/capabilities`}>Capabilities</a><a href={`${base}/how`}>How it works</a><a href={`${base}/docs`}>Docs</a></nav><div className="agency-nav-end"><span className="agency-clock">--:--:-- UTC</span><a href="https://x.com/tryagency" target="_blank" rel="noreferrer" aria-label="AGENCY on X">𝕏</a><a className="agency-launch" href={`${base}/launch`}>Launch</a><a className="agency-wallet" href="https://phantom.app/">Get Phantom</a></div></div></header>; }
export function DirectoryHero() { return <header className="agency-hero"><div><div className="agency-eyebrow">Directory</div><h1>All coins</h1><p>Every coin launched on AGENCY and every agent with its own wallet, with the mind that runs it. Sort by what matters, or filter by the model doing the thinking.</p></div><dl className="agency-hero-stats">{[['Coins','4,828'],['Awake','11'],['Providers','10'],['Graduated','178']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></header>; }
export function ProviderRail({ active }: { active?: string }) { return <aside className="agency-rail" aria-label="Filter by mind"><div className="agency-rail-title">Mind</div>{providers.map(([slug,name,count])=><a className={`agency-rail-item ${(!active && !slug || active === slug) ? 'on' : ''}`} href={slug ? `/coins?provider=${slug}` : '/coins'} key={name}><Icon name={name}/><span>{name}</span><span className="agency-rail-count">{count}</span></a>)}</aside>; }
function optionHref(params: Params, key: keyof Params, value: string) { const p = new URLSearchParams(); for (const [k,v] of Object.entries(params)) if (v && k !== key) p.set(k,v); if(value)p.set(key,value); return `/coins${p.size ? `?${p.toString()}` : ''}`; }
function Segment({ label, values, selected, params, param }: { label:string; values:[string,string][]; selected:string; params:Params; param:keyof Params }) { return <div className="agency-seg" role="tablist" aria-label={label}>{values.map(([value,name])=><a key={name} role="tab" aria-selected={selected===value} className={selected===value?'on':''} href={optionHref(params,param,value)}>{name}</a>)}</div>; }
export function DirectoryFilters({ params }: { params: Params }) { return <div className="agency-toolbar"><form action="/coins" className="agency-search"><input name="q" aria-label="Search coins" placeholder="Search name, ticker or mint" defaultValue={params.q || ''} />{params.provider && <input type="hidden" name="provider" value={params.provider}/>}</form><Segment label="Sort" values={[["","Top"],["new","New"],["fees","Most fees"],["awake","Awake first"]]} selected={params.sort||''} params={params} param="sort"/><Segment label="State" values={[["","All"],["awake","Awake"],["asleep","Asleep"],["graduated","Graduated"]]} selected={params.state||''} params={params} param="state"/></div>; }
export function CoinCard({ coin }: { coin: Coin }) { return <a className="agency-card" href={`${base}${coin.href}`}><div className="agency-card-media"><img src={coin.image} alt="" loading="lazy"/><span className={`agency-rank ${coin.agent?'agency-agent':''}`}>#{String(coin.rank).padStart(2,'0')}{coin.agent?' · AGENT':''}</span><span className={`agency-state ${coin.state.toLowerCase()}`}>{coin.state}</span></div><div className="agency-card-body"><div className="agency-card-title"><span className="agency-card-name">{coin.name}</span><span className="agency-symbol">{coin.symbol}</span></div><dl className="agency-card-stats"><div><dt>MCAP</dt><dd>{coin.mcap}</dd></div><div><dt>FEES</dt><dd>{coin.fees}</dd></div><div><dt>AGE</dt><dd>{coin.age}</dd></div></dl><div className="agency-mind"><Icon name={coin.provider}/><span className="agency-model">{coin.model}</span><span className="agency-maker">{coin.provider}</span></div></div></a>; }
export function AgencyFooter() { return <footer className="agency-footer"><div className="agency-wrap agency-footer-grid"><div><strong>AGENCY</strong><p>Every coin gets a mind. Minds act only through a deterministic policy engine and an isolated signer. Nothing here is financial advice.</p></div><div><strong>PLATFORM</strong><a href={`${base}/launch`}>Launch</a><a href={`${base}/coins`}>Explore</a><a href={`${base}/how`}>How it works</a></div><div><strong>DOCS</strong><a href={`${base}/docs`}>Economics</a><a href={`${base}/docs`}>Minds</a><a href={`${base}/docs`}>Firewall</a><a href={`${base}/docs`}>FAQ</a></div><div><strong>NETWORK</strong><span>Solana mainnet</span><span>Pump · PumpSwap</span><span>OpenRouter</span></div></div></footer>; }
