/**
 * Borsh coders built from the programs' IDLs (`idl/*.json`, the v2 builds, generated by `anchor idl
 * build` and copied by `scripts/sync-idl.mjs`). Instruction data, account data and events are
 * encoded and decoded through these, so the SDK never hand-writes a layout.
 */
import { createRequire } from 'node:module';
import anchor from '@anchor-lang/core';

const require = createRequire(import.meta.url);
const { BorshCoder, convertIdlToCamelCase } = anchor;
type Idl = Parameters<typeof convertIdlToCamelCase>[0];

export type Coder = InstanceType<typeof BorshCoder>;

/** The IDLs as built (snake_case names, PascalCase error names), one per program. */
export const IDL = {
  token: require('../idl/bordrless_token.json') as Idl,
  swap: require('../idl/bordrless_swap.json') as Idl,
  bridge: require('../idl/bordrless_bridge.json') as Idl,
  launch: require('../idl/bordrless_launch.json') as Idl,
  kit: require('../idl/bordrless_kit.json') as Idl,
  taxHook: require('../idl/tax_hook.json') as Idl,
  halfLife: require('../idl/half_life.json') as Idl,
  companion: require('../idl/bordrless_companion.json') as Idl,
};

function coder(idl: Idl): Coder {
  return new BorshCoder(convertIdlToCamelCase(idl));
}

/** Coders over the camel-cased IDLs: account names `holding`, `kitConfig`…, events `transferred`, `swapped`…. */
export const CODERS = {
  token: coder(IDL.token),
  swap: coder(IDL.swap),
  bridge: coder(IDL.bridge),
  launch: coder(IDL.launch),
  kit: coder(IDL.kit),
  taxHook: coder(IDL.taxHook),
  halfLife: coder(IDL.halfLife),
  companion: coder(IDL.companion),
};

export type ProgramName = keyof typeof CODERS;
