// Generated by scripts/gen-idl-types.mjs from app/packages/sdk/idl/*.json. Do not edit by hand.
import type { PublicKey } from '@solana/web3.js';

export namespace Token {
  export type AuthorityKind = 'Mint' | 'Freeze' | 'Hook' | 'Metadata';
  export interface AuthoritySet { mint: PublicKey; kind: number; newAuthority: PublicKey | null; ts: bigint; }
  export interface Burned { mint: PublicKey; source: PublicKey; sourceOwner: PublicKey; authority: PublicKey; amount: bigint; sourcePost: bigint; supplyPost: bigint; slot: bigint; ts: bigint; }
  export interface CreateMintArgs { decimals: number; name: string; symbol: string; uri: string; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; }
  export interface DelegateSet { mint: PublicKey; holding: PublicKey; delegate: PublicKey | null; amount: bigint; ts: bigint; }
  export interface DeltaApplied { holding: PublicKey; owner: PublicKey; amount: bigint; post: bigint; }
  export interface FrozenSet { mint: PublicKey; holding: PublicKey; frozen: boolean; ts: bigint; }
  export interface Holding { version: number; bump: number; mint: PublicKey; owner: PublicKey; amount: bigint; delegate: PublicKey | null; delegatedAmount: bigint; frozen: boolean; hookData: Buffer; voteLocked: bigint; voteLockUntil: bigint; }
  export interface HoldingClosed { mint: PublicKey; holding: PublicKey; owner: PublicKey; ts: bigint; }
  export interface HoldingCreated { mint: PublicKey; holding: PublicKey; owner: PublicKey; payer: PublicKey; ts: bigint; }
  export interface HookDataWritten { mint: PublicKey; holding: PublicKey; owner: PublicKey; data: Buffer; }
  export interface HookSet { mint: PublicKey; hookProgram: PublicKey | null; hookFlags: number; ts: bigint; }
  export interface MetadataUpdated { mint: PublicKey; name: string; symbol: string; uri: string; ts: bigint; }
  export interface Mint { version: number; decimals: number; supply: bigint; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; createdAt: bigint; creator: PublicKey; hookSignerBump: number; reserved: Buffer; slotAuthority: PublicKey | null; slotCount: number; slots: (Slot)[]; }
  export interface MintCreated { mint: PublicKey; creator: PublicKey; decimals: number; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; ts: bigint; }
  export interface Minted { mint: PublicKey; destination: PublicKey; destinationOwner: PublicKey; authority: PublicKey; amount: bigint; destinationPost: bigint; supplyPost: bigint; slot: bigint; ts: bigint; }
  export interface Slot { kind: number; equipRule: number; bounds: SlotBounds; dataOffset: number; dataLen: number; item: PublicKey; program: PublicKey; flags: number; poolFlags: number; equipVault: PublicKey; signerBump: number; launchSignerBump: number; dataEpoch: number; extraCount: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface SlotCut { slot: number; item: PublicKey; cut: bigint; }
  export interface SlotEquipped { mint: PublicKey; slot: number; oldItem: PublicKey; newItem: PublicKey; program: PublicKey; flags: number; poolFlags: number; dataEpoch: number; ts: bigint; }
  export interface SlotInfo { kind: number; equipRule: number; maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; dataOffset: number; dataLen: number; equipVault: PublicKey; lockedProgram: PublicKey; }
  export interface SlotInit { kind: number; equipRule: number; bounds: SlotBounds; dataLen: number; lockedProgram: PublicKey | null; lockedFlags: number; lockedExtraCount: number; }
  export interface SlotsInitialized { mint: PublicKey; slotAuthority: PublicKey | null; slots: (SlotInfo)[]; }
  export interface Transferred { mint: PublicKey; source: PublicKey; destination: PublicKey; sourceOwner: PublicKey; destinationOwner: PublicKey; authority: PublicKey; amount: bigint; deltas: (DeltaApplied)[]; sourcePost: bigint; destinationPost: bigint; slot: bigint; ts: bigint; slotCuts: (SlotCut)[]; }
  export interface VoteLockSet { mint: PublicKey; holding: PublicKey; owner: PublicKey; amount: bigint; until: bigint; ts: bigint; }
}

export namespace Armory {
  export interface AdminAccepted { admin: PublicKey; ts: bigint; }
  export interface AdminProposed { admin: PublicKey; readyAt: bigint; }
  export interface ArmoryConfig { version: number; bump: number; admin: PublicKey; pendingAdmin: PublicKey | null; pendingAdminAt: bigint; itemsMinted: bigint; templates: number; params: ArmoryParams; reserved: Buffer; }
  export interface ArmoryParams { maxRoyaltyBps: number; votePeriodSecs: number; voteQuorumBps: number; minNoticeSecs: number; maxNoticeSecs: number; forgeGainBps: number; minTwapSecs: number; maxPoolItemCutBps: number; maxPoolItemDiscountBps: number; maxItemReads: number; adminTimelockSecs: number; settleBountyBps: number; }
  export interface CompositeItem { version: number; bump: number; item: PublicKey; modules: (Module)[]; provenance: (PublicKey)[]; }
  export interface EquipApplied { mint: PublicKey; slot: number; oldItem: PublicKey | null; newItem: PublicKey | null; by: number; ts: bigint; }
  export interface EquipConfig { targets: (PublicKey)[]; role: number; }
  export interface ForgeCounter { wallet: PublicKey; count: bigint; bump: number; }
  export interface Forged { burned: (PublicKey)[]; item: PublicKey; templateId: number; params: (number)[]; level: number; forger: PublicKey; ts: bigint; }
  export interface Item { version: number; bump: number; itemMint: PublicKey; templateId: number; params: (number)[]; manifest: Manifest; author: PublicKey; royaltyBps: number; level: number; source: number; equippedCount: number; royaltyOwnerBump: number; createdAt: bigint; reserved: Buffer; }
  export interface ItemCreated { item: PublicKey; itemMint: PublicKey; templateId: number; params: (number)[]; manifest: Manifest; author: PublicKey; royaltyBps: number; level: number; source: number; ts: bigint; }
  export interface LaunchEquip { slot: number; item: PublicKey | null; config: EquipConfig; noticeSecs: number; rule: PerformanceRule | null; }
  export interface LootMinted { item: PublicKey; owner: PublicKey; templateId: number; params: (number)[]; ts: bigint; }
  export interface Manifest { kind: number; tokenFlags: number; poolFlags: number; maxCutBuyBps: number; maxCutSellBps: number; maxCutTransferBps: number; maxDiscountBps: number; mayRefuse: boolean; mayBurn: boolean; dataBytes: number; readsOtherPools: number; }
  export interface Module { templateId: number; params: (number)[]; targetStart: number; targetCount: number; dataBytes: number; readsModule: number; }
  export interface ParamsApplied { params: ArmoryParams; ts: bigint; }
  export interface ParamsProposed { params: ArmoryParams; readyAt: bigint; }
  export interface PendingParams { bump: number; params: ArmoryParams; readyAt: bigint; }
  export interface PerformanceCondition { mint: PublicKey; slot: number; trueSince: bigint | null; }
  export interface PerformanceReverted { mint: PublicKey; slot: number; fromItem: PublicKey | null; toItem: PublicKey | null; ts: bigint; }
  export interface PerformanceRule { metric: number; windowSecs: number; baseWindowSecs: number; op: number; ratioBps: number; holdSecs: number; }
  export interface Pool { version: number; bump: number; lpMintBump: number; baseMint: PublicKey; quoteMint: PublicKey; lpMint: PublicKey; baseVault: PublicKey; quoteVault: PublicKey; hookProgram: PublicKey | null; hookFlags: number; lpFeeBps: number; protocolFeeBps: number; baseReserve: bigint; quoteReserve: bigint; virtualBase: bigint; virtualQuote: bigint; lpSupply: bigint; protocolFeesQuote: bigint; curve: boolean; creator: PublicKey; createdAt: bigint; lastSwapAt: bigint; swapCount: bigint; baseVolume: bigint; quoteVolume: bigint; hookSignerBump: number; feeModel: number; protocolShareBps: number; reserved: Buffer; }
  export interface Proposal { version: number; bump: number; mint: PublicKey; slot: number; nonce: bigint; proposer: PublicKey; item: PublicKey | null; config: EquipConfig; createdAt: bigint; voteEnd: bigint; executableAt: bigint; votesFor: bigint; votesAgainst: bigint; votersOpen: number; status: number; reserved: Buffer; }
  export interface ProposalCreated { mint: PublicKey; slot: number; nonce: bigint; proposer: PublicKey; item: PublicKey | null; voteEnd: bigint; executableAt: bigint; }
  export interface ProposalResolved { proposal: PublicKey; status: number; votesFor: bigint; votesAgainst: bigint; eligible: bigint; ts: bigint; }
  export interface RegisterTemplateArgs { id: number; codeHash: Buffer; kind: number; fieldCount: number; fieldMin: (number)[]; fieldMax: (number)[]; openAuthoring: boolean; lootEnabled: boolean; forgeEnabled: boolean; maxLevel: number; lootRoyaltyBps: number; maxTargets: number; name: string; }
  export interface RoyaltyClaimed { item: PublicKey; cutMint: PublicKey; claimant: PublicKey; amount: bigint; ts: bigint; }
  export interface SlotState { version: number; bump: number; mint: PublicKey; slot: number; equipRule: number; noticeSecs: number; launchItem: PublicKey | null; launchConfig: EquipConfig; rule: PerformanceRule | null; openProposal: bigint | null; nextNonce: bigint; conditionSince: bigint | null; lastCheck: bigint; reserved: Buffer; }
  export interface Template { version: number; bump: number; id: number; program: PublicKey; codeHash: Buffer; deploySlot: bigint | null; kind: number; fieldCount: number; fieldMin: (number)[]; fieldMax: (number)[]; openAuthoring: boolean; lootEnabled: boolean; forgeEnabled: boolean; maxLevel: number; lootRoyaltyBps: number; maxTargets: number; status: number; name: string; registeredBy: PublicKey; createdAt: bigint; reserved: Buffer; }
  export interface TemplateRegistered { templateId: number; program: PublicKey; codeHash: Buffer; deploySlot: bigint | null; kind: number; fieldCount: number; fieldMin: (number)[]; fieldMax: (number)[]; name: string; ts: bigint; }
  export interface TemplateRetired { templateId: number; ts: bigint; }
  export interface VoteLock { proposal: PublicKey; voter: PublicKey; amount: bigint; support: boolean; bump: number; }
  export interface VoteLocked { proposal: PublicKey; voter: PublicKey; support: boolean; amount: bigint; until: bigint; }
  export interface VoteUnlocked { proposal: PublicKey; voter: PublicKey; amount: bigint; }
}

export namespace Items {
  export interface EquipClosed { mint: PublicKey; slot: number; item: PublicKey; }
  export interface EquipConfig { targets: (PublicKey)[]; role: number; }
  export interface EquipInitialized { mint: PublicKey; slot: number; item: PublicKey; config: EquipConfig; }
  export interface EquipSettled { mint: PublicKey; slot: number; item: PublicKey; royaltyToken: bigint; royaltyQuote: bigint; amountToken: bigint; amountQuote: bigint; burned: bigint; bountyToken: bigint; bountyQuote: bigint; }
  export interface EquipState { version: number; bump: number; mint: PublicKey; slot: number; item: PublicKey; templateId: number; config: EquipConfig; equippedAt: bigint; runs: bigint; collectedToken: bigint; poolOwed: bigint; poolSettled: bigint; tokenUnsettled: (bigint)[]; poolUnsettled: (bigint)[]; reserved: Buffer; }
  export interface ItemCut { mint: PublicKey; slot: number; item: PublicKey; module: number; side: number; amount: bigint; }
  export interface ItemPoolContext { slot: number; item: PublicKey; launchFeeBps: number; launchCut: bigint; sideAmount: bigint; }
  export interface Manifest { kind: number; tokenFlags: number; poolFlags: number; maxCutBuyBps: number; maxCutSellBps: number; maxCutTransferBps: number; maxDiscountBps: number; mayRefuse: boolean; mayBurn: boolean; dataBytes: number; readsOtherPools: number; }
  export type Phase = 'Before' | 'After';
  export interface PoolHookArgs { op: PoolOp; phase: Phase; pool: PublicKey; baseMint: PublicKey; quoteMint: PublicKey; actor: PublicKey; recipient: PublicKey; direction: number; amountIn: bigint; amountOut: bigint; baseReserve: bigint; quoteReserve: bigint; virtualBase: bigint; virtualQuote: bigint; lpFeeBps: number; protocolFeeBps: number; swapCount: bigint; createdAt: bigint; lpAmount: bigint; hookData: Buffer; route: RouteContext; }
  export type PoolOp = 'Initialize' | 'AddLiquidity' | 'RemoveLiquidity' | 'Swap';
  export interface RaidMarked { mint: PublicKey; rival: PublicKey; trader: PublicKey; volume: bigint; points: number; lootTicket: boolean; }
  export interface RouteContext { routeInputMint: PublicKey; routeOutputMint: PublicKey; firstPool: PublicKey; routeAmountIn: bigint; hopIndex: number; hopCount: number; }
  export interface ShieldTaken { mint: PublicKey; owner: PublicKey; cut: bigint; }
  export interface TokenSlotArgs { op: TokenSlotOp; phase: Phase; slot: number; item: PublicKey; mint: PublicKey; source: PublicKey; destination: PublicKey; sourceOwner: PublicKey; destinationOwner: PublicKey; authority: PublicKey; authorityIsDelegate: boolean; amount: bigint; delta: bigint; totalDelta: bigint; sourceBalance: bigint; destinationBalance: bigint; decimals: number; supply: bigint; sourceData: Buffer; destinationData: Buffer; payload: Buffer; }
  export type TokenSlotOp = 'Transfer' | 'Burn' | 'Touch';
}

export namespace War {
  export interface BountyClaimed { mint: PublicKey; owner: PublicKey; points: number; paid: bigint; }
  export interface CandidateChallenged { season: number; mint: PublicKey; score: bigint; submittedBy: PublicKey; beaten: PublicKey; }
  export interface CandidateSubmitted { season: number; mint: PublicKey; score: bigint; submittedBy: PublicKey; }
  export interface Captured { rivalMint: PublicKey; amount: bigint; cost: bigint; capturedAt: bigint; razeWindowStart: bigint; razeWindowBase: bigint; razedInWindow: bigint; }
  export interface CapturedReturned { mint: PublicKey; rivalMint: PublicKey; amount: bigint; treatyItem: PublicKey; }
  export interface ConfigApplied { change: ConfigChange; eta: bigint; }
  export interface ConfigArgs { admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; params: WarParams; }
  export interface ConfigChange { admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; params: WarParams; }
  export interface ConfigProposed { change: ConfigChange; eta: bigint; }
  export interface CounterStrikeExecuted { mint: PublicKey; spent: bigint; burned: bigint; bounty: bigint; cranker: PublicKey; }
  export interface Launch { version: number; bump: number; mint: PublicKey; creator: PublicKey; pool: PublicKey; quoteMint: PublicKey; status: number; creatorFeeBps: number; lpFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; virtualQuote: bigint; virtualBase: bigint; graduationQuote: bigint; curveTokens: bigint; reserveTokens: bigint; reserveHolding: PublicKey; quoteHolding: PublicKey; lpHolding: PublicKey; createdAt: bigint; graduatedAt: bigint; creatorFeesAccrued: bigint; creatorFeesClaimed: bigint; graduationTopup: bigint; graduationBurned: bigint; rules: LaunchRules; modules: number; kitConfig: PublicKey; holderVault: PublicKey; kitCallerBump: number; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; creatorBought: boolean; holderFeesAccrued: bigint; burnedOnTrades: bigint; config: PublicKey; customHook: PublicKey | null; customHookFlags: number; authorShareBps: number; authorFeesPaid: bigint; slotLaunch: number; reserved: Buffer; }
  export interface LaunchRules { holderFeeBuyBps: number; holderFeeSellBps: number; burnBuyBps: number; burnSellBps: number; maxWalletBps: number; creatorLockSecs: number; earlyWindowSecs: number; earlyLockSecs: number; }
  export interface LootEntry { templateId: number; weight: number; ranges: (ParamRange)[]; }
  export interface LootTable { version: number; bump: number; season: number; count: number; entries: (LootEntry)[]; eta: bigint; }
  export interface LootTableProposed { season: number; eta: bigint; }
  export interface Mint { version: number; decimals: number; supply: bigint; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; createdAt: bigint; creator: PublicKey; hookSignerBump: number; reserved: Buffer; slotAuthority: PublicKey | null; slotCount: number; slots: (Slot)[]; }
  export interface ParamRange { min: number; max: number; }
  export interface PendingCancelled { what: number; season: number; eta: bigint; }
  export interface PendingConfig { admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; params: WarParams; eta: bigint; }
  export interface PrizePaid { season: number; winner: PublicKey | null; toWinner: bigint; toTreasury: bigint; bounty: bigint; cranker: PublicKey; }
  export interface QuestClaimed { questId: number; mint: PublicKey; owner: PublicKey; season: number; period: number; }
  export interface QuestMark { version: number; bump: number; season: number; mint: PublicKey; owner: PublicKey; lastPeriod: number; lastForgeCount: bigint; }
  export interface Razed { mint: PublicKey; rivalMint: PublicKey; sold: bigint; got: bigint; bounty: bigint; cranker: PublicKey; capturedLeft: bigint; }
  export interface RollCancelled { roll: PublicKey; mint: PublicKey; owner: PublicKey; }
  export interface RollRequest { version: number; bump: number; owner: PublicKey; mint: PublicKey; holding: PublicKey; nonce: bigint; season: number; requestedSlot: bigint; requestedAt: bigint; oracleProgram: PublicKey; oracleAccount: PublicKey; }
  export interface RollRequested { roll: PublicKey; mint: PublicKey; owner: PublicKey; holding: PublicKey; season: number; requestedSlot: bigint; oracleProgram: PublicKey; oracleAccount: PublicKey; }
  export interface RollRevealed { roll: PublicKey; mint: PublicKey; owner: PublicKey; item: PublicKey; templateId: number; params: (number)[]; season: number; }
  export interface ScoreWeights { raidVolumeWon: bigint; sieges: bigint; siegeSpend: bigint; timesBesieged: bigint; counterStrikes: bigint; treatySecs: bigint; }
  export interface Season { version: number; bump: number; number: number; startsAt: bigint; endsAt: bigint; weights: ScoreWeights; penalizeBesieged: boolean; eta: bigint; opened: boolean; leader: PublicKey | null; leaderScore: bigint; finalized: boolean; prizePaid: bigint; reserved: Buffer; }
  export interface SeasonArgs { number: number; startsAt: bigint; weights: ScoreWeights; penalizeBesieged: boolean; }
  export interface SeasonCounters { raidVolumeWon: bigint; sieges: number; siegeSpend: bigint; timesBesieged: number; counterStrikes: number; treatySecs: bigint; }
  export interface SeasonFinalized { season: number; winner: PublicKey | null; score: bigint; }
  export interface SeasonOpened { season: number; startsAt: bigint; endsAt: bigint; }
  export interface SeasonProposed { season: number; startsAt: bigint; endsAt: bigint; weights: ScoreWeights; penalizeBesieged: boolean; eta: bigint; }
  export interface SiegeExecuted { mint: PublicKey; rivalMint: PublicKey; spent: bigint; bought: bigint; bounty: bigint; cranker: PublicKey; capturedTotal: bigint; }
  export interface SiegeWaited { mint: PublicKey; rivalMint: PublicKey; rivalPrice: bigint; rivalTwap: bigint; }
  export interface SliceArgs { first: number; second: number; }
  export interface Slot { kind: number; equipRule: number; bounds: SlotBounds; dataOffset: number; dataLen: number; item: PublicKey; program: PublicKey; flags: number; poolFlags: number; equipVault: PublicKey; signerBump: number; launchSignerBump: number; dataEpoch: number; extraCount: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface TreatyInflowShared { mint: PublicKey; amount: bigint; bounty: bigint; cranker: PublicKey; }
  export interface TreatyTimeAccrued { mint: PublicKey; treatyItem: PublicKey; secs: bigint; season: number; }
  export interface WarChestCreated { mint: PublicKey; chest: PublicKey; treatyInbox: PublicKey; warState: PublicKey; }
  export interface WarConfig { version: number; bump: number; prizeVaultBump: number; admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; currentSeason: number; lastWinner: PublicKey | null; lastWinnerSeason: number; params: WarParams; pending: PendingConfig | null; reserved: Buffer; }
  export interface WarFunded { mint: PublicKey; amount: bigint; balance: bigint; fundedTotal: bigint; }
  export interface WarParams { adminTimelockSecs: bigint; maxCrankBountyBps: number; siegeIntervalSecs: bigint; siegeMaxSpendBps: number; siegeMaxPremiumBps: number; siegeSlippageBps: number; siegeUnitLamports: bigint; counterMaxSpendBps: number; counterMinIntervalSecs: bigint; razeMaxBpsPerInterval: number; razeIntervalSecs: bigint; bountyMaxPerClaim: bigint; minTwapSecs: bigint; raidWindowSecs: bigint; rollExpirySecs: bigint; questPeriodSecs: bigint; questRaidPoints: number; seasonSecs: bigint; challengeSecs: bigint; seasonPrizeShareBps: number; pointUnitLamports: bigint; lootMinRaidLamports: bigint; }
  export interface WarState { version: number; bump: number; chestBump: number; inboxBump: number; mint: PublicKey; launch: PublicKey; lastSeenBalance: bigint; fundedTotal: bigint; spentSiege: bigint; spentCounter: bigint; paidBounties: bigint; paidCranks: bigint; razedProceeds: bigint; treatySharedTotal: bigint; lastSiegeAt: bigint; lastCounterAt: bigint; lastTreatyTick: bigint; underSiegeUntil: bigint; siegeByChest: PublicKey; captured: (Captured)[]; seasonId: number; season: SeasonCounters; prevSeason: SeasonCounters; reserved: Buffer; }
}

export namespace Kit {
  export interface Delta { amount: bigint; account: number; }
  export interface Holding { version: number; bump: number; mint: PublicKey; owner: PublicKey; amount: bigint; delegate: PublicKey | null; delegatedAmount: bigint; frozen: boolean; hookData: Buffer; voteLocked: bigint; voteLockUntil: bigint; }
  export interface HookReturn { deltas: (Delta)[]; burn: bigint; lpFeeBps: number | null; sourceHookData: Buffer | null; destinationHookData: Buffer | null; }
  export interface KitConfig { version: number; bump: number; kitCallerBump: number; modules: number; graduated: boolean; eligible: bigint; minEligible: bigint; mint: PublicKey; launch: PublicKey; pool: PublicKey; creator: PublicKey; rewardMint: PublicKey; rewardVault: PublicKey; supplyAtInit: bigint; maxWalletBps: number; maxWalletAmount: bigint; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; accPerShare: bigint; rem: bigint; held: bigint; seen: bigint; streamRemaining: bigint; streamLast: bigint; streamEnd: bigint; totalDistributed: bigint; totalClaimed: bigint; totalShared: bigint; createdAt: bigint; streamNext: bigint; creatorIsCompanion: boolean; reserved: Buffer; }
  export interface KitGraduated { mint: PublicKey; ts: bigint; }
  export interface KitInitArgs { launch: PublicKey; pool: PublicKey; creator: PublicKey; rewardMint: PublicKey; modules: number; maxWalletBps: number; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; kitCallerBump: number; }
  export interface KitInstalled { mint: PublicKey; kitConfig: PublicKey; launch: PublicKey; pool: PublicKey; creator: PublicKey; rewardMint: PublicKey; rewardVault: PublicKey; modules: number; supply: bigint; minEligible: bigint; maxWalletBps: number; maxWalletAmount: bigint; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; ts: bigint; }
  export interface Mint { version: number; decimals: number; supply: bigint; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; createdAt: bigint; creator: PublicKey; hookSignerBump: number; reserved: Buffer; slotAuthority: PublicKey | null; slotCount: number; slots: (Slot)[]; }
  export type Phase = 'Before' | 'After';
  export interface RewardsClaimed { mint: PublicKey; owner: PublicKey; amount: bigint; owedLeft: bigint; totalClaimed: bigint; }
  export interface RewardsShared { mint: PublicKey; from: PublicKey; amount: bigint; totalShared: bigint; }
  export interface Slot { kind: number; equipRule: number; bounds: SlotBounds; dataOffset: number; dataLen: number; item: PublicKey; program: PublicKey; flags: number; poolFlags: number; equipVault: PublicKey; signerBump: number; launchSignerBump: number; dataEpoch: number; extraCount: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface TokenHookArgs { op: TokenOp; phase: Phase; mint: PublicKey; source: PublicKey; destination: PublicKey; sourceOwner: PublicKey; destinationOwner: PublicKey; authority: PublicKey; authorityIsDelegate: boolean; amount: bigint; delta: bigint; sourceBalance: bigint; destinationBalance: bigint; decimals: number; supply: bigint; sourceHookData: Buffer; destinationHookData: Buffer; }
  export type TokenOp = 'Transfer' | 'Mint' | 'Burn';
}

export namespace Companion {
  export interface BeneficiaryPaid { companion: PublicKey; lamports: bigint; }
  export interface BoughtBack { companion: PublicKey; spent: bigint; burned: bigint; bounty: bigint; cranker: PublicKey; }
  export interface BuybackWaited { companion: PublicKey; price: bigint; reference: bigint; }
  export interface Companion { version: number; bump: number; creatorBump: number; mint: PublicKey; beneficiary: PublicKey; split: Split; bountyBps: number; maxBuyback: bigint; buybackInterval: bigint; vestSecs: bigint; launched: boolean; launchedAt: bigint; devTokens: bigint; devReleased: bigint; pendingBuyback: bigint; pendingHolders: bigint; pendingBeneficiary: bigint; lastBuybackAt: bigint; claimedTotal: bigint; spentTotal: bigint; burnedTotal: bigint; sharedTotal: bigint; paidBeneficiaryTotal: bigint; bountiesTotal: bigint; referencePrice: bigint; referenceAt: bigint; warTotal: bigint; reserved: Buffer; }
  export interface CompanionCreated { companion: PublicKey; mint: PublicKey; creator: PublicKey; beneficiary: PublicKey; split: Split; bountyBps: number; maxBuyback: bigint; buybackInterval: bigint; vestSecs: bigint; }
  export interface CompanionLaunched { companion: PublicKey; mint: PublicKey; ts: bigint; }
  export interface CompanionWarFunded { companion: PublicKey; mint: PublicKey; warChest: PublicKey; amount: bigint; warTotal: bigint; }
  export interface CreateArgs { split: Split; bountyBps: number; maxBuyback: bigint; buybackInterval: bigint; vestSecs: bigint; fund: bigint; }
  export interface CreateLaunchArgs { name: string; symbol: string; uri: string; creatorFeeBps: number; virtualQuote: bigint; rules: LaunchRules; }
  export interface DevBought { companion: PublicKey; lamports: bigint; tokens: bigint; devTokens: bigint; }
  export interface DevReleased { companion: PublicKey; tokens: bigint; released: bigint; }
  export interface FeesClaimed { companion: PublicKey; claimed: bigint; bounty: bigint; toBuyback: bigint; toHolders: bigint; toBeneficiary: bigint; cranker: PublicKey; }
  export interface Launch { version: number; bump: number; mint: PublicKey; creator: PublicKey; pool: PublicKey; quoteMint: PublicKey; status: number; creatorFeeBps: number; lpFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; virtualQuote: bigint; virtualBase: bigint; graduationQuote: bigint; curveTokens: bigint; reserveTokens: bigint; reserveHolding: PublicKey; quoteHolding: PublicKey; lpHolding: PublicKey; createdAt: bigint; graduatedAt: bigint; creatorFeesAccrued: bigint; creatorFeesClaimed: bigint; graduationTopup: bigint; graduationBurned: bigint; rules: LaunchRules; modules: number; kitConfig: PublicKey; holderVault: PublicKey; kitCallerBump: number; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; creatorBought: boolean; holderFeesAccrued: bigint; burnedOnTrades: bigint; config: PublicKey; customHook: PublicKey | null; customHookFlags: number; authorShareBps: number; authorFeesPaid: bigint; slotLaunch: number; reserved: Buffer; }
  export interface LaunchRules { holderFeeBuyBps: number; holderFeeSellBps: number; burnBuyBps: number; burnSellBps: number; maxWalletBps: number; creatorLockSecs: number; earlyWindowSecs: number; earlyLockSecs: number; }
  export interface SharedWithHolders { companion: PublicKey; amount: bigint; bounty: bigint; cranker: PublicKey; }
  export interface Split { buybackBps: number; holdersBps: number; beneficiaryBps: number; warBps: number; }
}
