// Generated by scripts/gen-idl-types.mjs from app/packages/sdk/idl/*.json. Do not edit by hand.
import type { PublicKey } from '@solana/web3.js';

export namespace Token {
  export type AuthorityKind = 'Mint' | 'Freeze' | 'Hook' | 'Metadata';
  export interface AuthoritySet { mint: PublicKey; kind: number; newAuthority: PublicKey | null; ts: bigint; }
  export interface Burned { mint: PublicKey; source: PublicKey; sourceOwner: PublicKey; authority: PublicKey; amount: bigint; sourcePost: bigint; supplyPost: bigint; slot: bigint; ts: bigint; }
  export interface CreateMintArgs { decimals: number; name: string; symbol: string; uri: string; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; }
  export interface DelegateSet { mint: PublicKey; holding: PublicKey; delegate: PublicKey | null; amount: bigint; ts: bigint; }
  export interface DeltaApplied { holding: PublicKey; owner: PublicKey; amount: bigint; post: bigint; }
  export interface FrozenSet { mint: PublicKey; holding: PublicKey; frozen: boolean; ts: bigint; }
  export interface Holding { version: number; bump: number; mint: PublicKey; owner: PublicKey; amount: bigint; delegate: PublicKey | null; delegatedAmount: bigint; frozen: boolean; hookData: Buffer; voteLocked: bigint; voteLockUntil: bigint; }
  export interface HoldingClosed { mint: PublicKey; holding: PublicKey; owner: PublicKey; ts: bigint; }
  export interface HoldingCreated { mint: PublicKey; holding: PublicKey; owner: PublicKey; payer: PublicKey; ts: bigint; }
  export interface HookDataWritten { mint: PublicKey; holding: PublicKey; owner: PublicKey; data: Buffer; }
  export interface HookSet { mint: PublicKey; hookProgram: PublicKey | null; hookFlags: number; ts: bigint; }
  export interface MetadataUpdated { mint: PublicKey; name: string; symbol: string; uri: string; ts: bigint; }
  export interface Mint { version: number; decimals: number; supply: bigint; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; createdAt: bigint; creator: PublicKey; hookSignerBump: number; reserved: Buffer; slotAuthority: PublicKey | null; slotCount: number; slots: (Slot)[]; }
  export interface MintCreated { mint: PublicKey; creator: PublicKey; decimals: number; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; ts: bigint; }
  export interface Minted { mint: PublicKey; destination: PublicKey; destinationOwner: PublicKey; authority: PublicKey; amount: bigint; destinationPost: bigint; supplyPost: bigint; slot: bigint; ts: bigint; }
  export interface Slot { kind: number; equipRule: number; bounds: SlotBounds; dataOffset: number; dataLen: number; item: PublicKey; program: PublicKey; flags: number; poolFlags: number; equipVault: PublicKey; signerBump: number; launchSignerBump: number; dataEpoch: number; extraCount: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface SlotCut { slot: number; item: PublicKey; cut: bigint; }
  export interface SlotEquipped { mint: PublicKey; slot: number; oldItem: PublicKey; newItem: PublicKey; program: PublicKey; flags: number; poolFlags: number; dataEpoch: number; ts: bigint; }
  export interface SlotInfo { kind: number; equipRule: number; maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; dataOffset: number; dataLen: number; equipVault: PublicKey; lockedProgram: PublicKey; }
  export interface SlotInit { kind: number; equipRule: number; bounds: SlotBounds; dataLen: number; lockedProgram: PublicKey | null; lockedFlags: number; lockedExtraCount: number; }
  export interface SlotsInitialized { mint: PublicKey; slotAuthority: PublicKey | null; slots: (SlotInfo)[]; }
  export interface Transferred { mint: PublicKey; source: PublicKey; destination: PublicKey; sourceOwner: PublicKey; destinationOwner: PublicKey; authority: PublicKey; amount: bigint; deltas: (DeltaApplied)[]; sourcePost: bigint; destinationPost: bigint; slot: bigint; ts: bigint; slotCuts: (SlotCut)[]; }
  export interface VoteLockSet { mint: PublicKey; holding: PublicKey; owner: PublicKey; amount: bigint; until: bigint; ts: bigint; }
}

export namespace Armory {
  export interface AdminAccepted { admin: PublicKey; ts: bigint; }
  export interface AdminProposed { admin: PublicKey; readyAt: bigint; }
  export interface ArmoryConfig { version: number; bump: number; admin: PublicKey; pendingAdmin: PublicKey | null; pendingAdminAt: bigint; itemsMinted: bigint; templates: number; params: ArmoryParams; itemProtocolBps: number; reserved: Buffer; }
  export interface ArmoryParams { maxRoyaltyBps: number; votePeriodSecs: number; voteQuorumBps: number; minNoticeSecs: number; maxNoticeSecs: number; forgeGainBps: number; minTwapSecs: number; maxPoolItemCutBps: number; maxPoolItemDiscountBps: number; maxItemReads: number; adminTimelockSecs: number; settleBountyBps: number; proposalMinBps: number; }
  export interface AuthorCounter { wallet: PublicKey; items: bigint; bump: number; }
  export interface ClaimCounter { wallet: PublicKey; lamports: bigint; bump: number; }
  export interface CompositeItem { version: number; bump: number; item: PublicKey; modules: (Module)[]; provenance: (PublicKey)[]; }
  export interface EquipApplied { mint: PublicKey; slot: number; oldItem: PublicKey | null; newItem: PublicKey | null; by: number; ts: bigint; }
  export interface EquipConfig { targets: (PublicKey)[]; role: number; }
  export interface ForgeCounter { wallet: PublicKey; count: bigint; bump: number; }
  export interface Forged { burned: (PublicKey)[]; item: PublicKey; templateId: number; params: (number)[]; level: number; forger: PublicKey; ts: bigint; }
  export interface FuseTarget { start: number; count: number; }
  export interface Item { version: number; bump: number; itemMint: PublicKey; templateId: number; params: (number)[]; manifest: Manifest; author: PublicKey; royaltyBps: number; level: number; source: number; equippedCount: number; royaltyOwnerBump: number; createdAt: bigint; hasWear: boolean; reserved: Buffer; }
  export interface ItemCrafted { item: PublicKey; owner: PublicKey; templateId: number; recipeId: number; params: (number)[]; ts: bigint; }
  export interface ItemCreated { item: PublicKey; itemMint: PublicKey; templateId: number; params: (number)[]; manifest: Manifest; author: PublicKey; royaltyBps: number; level: number; source: number; ts: bigint; }
  export interface ItemProtocolBpsSet { itemProtocolBps: number; }
  export interface LaunchEquip { slot: number; item: PublicKey | null; config: EquipConfig; noticeSecs: number; rule: PerformanceRule | null; }
  export interface LootMinted { item: PublicKey; owner: PublicKey; templateId: number; params: (number)[]; ts: bigint; }
  export interface Manifest { kind: number; tokenFlags: number; poolFlags: number; maxCutBuyBps: number; maxCutSellBps: number; maxCutTransferBps: number; maxDiscountBps: number; mayRefuse: boolean; mayBurn: boolean; dataBytes: number; readsOtherPools: number; }
  export interface Module { templateId: number; params: (number)[]; targetStart: number; targetCount: number; dataBytes: number; readsModule: number; }
  export interface ParamsApplied { params: ArmoryParams; ts: bigint; }
  export interface ParamsProposed { params: ArmoryParams; readyAt: bigint; }
  export interface PendingParams { bump: number; params: ArmoryParams; readyAt: bigint; }
  export interface PerformanceCondition { mint: PublicKey; slot: number; trueSince: bigint | null; }
  export interface PerformanceReverted { mint: PublicKey; slot: number; fromItem: PublicKey | null; toItem: PublicKey | null; ts: bigint; }
  export interface PerformanceRule { metric: number; windowSecs: number; baseWindowSecs: number; op: number; ratioBps: number; holdSecs: number; }
  export interface Pool { version: number; bump: number; lpMintBump: number; baseMint: PublicKey; quoteMint: PublicKey; lpMint: PublicKey; baseVault: PublicKey; quoteVault: PublicKey; hookProgram: PublicKey | null; hookFlags: number; lpFeeBps: number; protocolFeeBps: number; baseReserve: bigint; quoteReserve: bigint; virtualBase: bigint; virtualQuote: bigint; lpSupply: bigint; protocolFeesQuote: bigint; curve: boolean; creator: PublicKey; createdAt: bigint; lastSwapAt: bigint; swapCount: bigint; baseVolume: bigint; quoteVolume: bigint; hookSignerBump: number; feeModel: number; protocolShareBps: number; reserved: Buffer; }
  export interface Preset { version: number; bump: number; id: number; name: string; templateIds: (number)[]; registeredAt: bigint; }
  export interface PresetRegistered { id: number; templateIds: (number)[]; }
  export interface Proposal { version: number; bump: number; mint: PublicKey; slot: number; nonce: bigint; proposer: PublicKey; item: PublicKey | null; config: EquipConfig; createdAt: bigint; voteEnd: bigint; executableAt: bigint; votesFor: bigint; votesAgainst: bigint; votersOpen: number; status: number; reserved: Buffer; }
  export interface ProposalCreated { mint: PublicKey; slot: number; nonce: bigint; proposer: PublicKey; item: PublicKey | null; voteEnd: bigint; executableAt: bigint; }
  export interface ProposalResolved { proposal: PublicKey; status: number; votesFor: bigint; votesAgainst: bigint; eligible: bigint; ts: bigint; }
  export interface RegisterTemplateArgs { id: number; codeHash: Buffer; kind: number; fieldCount: number; fieldMin: (number)[]; fieldMax: (number)[]; openAuthoring: boolean; lootEnabled: boolean; forgeEnabled: boolean; maxLevel: number; lootRoyaltyBps: number; maxTargets: number; name: string; }
  export interface RoyaltyClaimed { item: PublicKey; cutMint: PublicKey; claimant: PublicKey; amount: bigint; ts: bigint; }
  export interface SlotState { version: number; bump: number; mint: PublicKey; slot: number; equipRule: number; noticeSecs: number; launchItem: PublicKey | null; launchConfig: EquipConfig; rule: PerformanceRule | null; openProposal: bigint | null; nextNonce: bigint; conditionSince: bigint | null; lastCheck: bigint; reserved: Buffer; }
  export interface Template { version: number; bump: number; id: number; program: PublicKey; codeHash: Buffer; deploySlot: bigint | null; kind: number; fieldCount: number; fieldMin: (number)[]; fieldMax: (number)[]; openAuthoring: boolean; lootEnabled: boolean; forgeEnabled: boolean; maxLevel: number; lootRoyaltyBps: number; maxTargets: number; status: number; name: string; registeredBy: PublicKey; createdAt: bigint; authorBps: number; defaultAccess: number; allowedAccess: number; chargesOnCreate: number; reserved: Buffer; }
  export interface TemplateEconomySet { templateId: number; authorBps: number; defaultAccess: number; allowedAccess: number; chargesOnCreate: number; }
  export interface TemplateRegistered { templateId: number; program: PublicKey; codeHash: Buffer; deploySlot: bigint | null; kind: number; fieldCount: number; fieldMin: (number)[]; fieldMax: (number)[]; name: string; ts: bigint; }
  export interface TemplateRetired { templateId: number; ts: bigint; }
  export interface VoteLock { proposal: PublicKey; voter: PublicKey; amount: bigint; support: boolean; bump: number; }
  export interface VoteLocked { proposal: PublicKey; voter: PublicKey; support: boolean; amount: bigint; until: bigint; }
  export interface VoteUnlocked { proposal: PublicKey; voter: PublicKey; amount: bigint; }
}

export namespace Items {
  export interface AuthorSharePaid { mint: PublicKey; slot: number; item: PublicKey; templateId: number; authorToken: bigint; authorQuote: bigint; }
  export interface EquipClosed { mint: PublicKey; slot: number; item: PublicKey; }
  export interface EquipConfig { targets: (PublicKey)[]; role: number; }
  export interface EquipInitialized { mint: PublicKey; slot: number; item: PublicKey; config: EquipConfig; }
  export interface EquipSettled { mint: PublicKey; slot: number; item: PublicKey; royaltyToken: bigint; royaltyQuote: bigint; amountToken: bigint; amountQuote: bigint; burned: bigint; bountyToken: bigint; bountyQuote: bigint; }
  export interface EquipState { version: number; bump: number; mint: PublicKey; slot: number; item: PublicKey; templateId: number; config: EquipConfig; equippedAt: bigint; runs: bigint; collectedToken: bigint; poolOwed: bigint; poolSettled: bigint; tokenUnsettled: (bigint)[]; poolUnsettled: (bigint)[]; runsAtSettle: bigint; reserved: Buffer; }
  export interface FirstBlood { version: number; bump: number; mint: PublicKey; lastDay: number; taken: boolean; }
  export interface ItemCut { mint: PublicKey; slot: number; item: PublicKey; module: number; side: number; amount: bigint; }
  export interface ItemPoolContext { slot: number; item: PublicKey; launchFeeBps: number; launchCut: bigint; sideAmount: bigint; }
  export interface LeaseRentPaid { mint: PublicKey; slot: number; item: PublicKey; lessor: PublicKey; rentToken: bigint; rentQuote: bigint; }
  export interface LoyaltyClaimed { mint: PublicKey; holder: PublicKey; epoch: number; balance: bigint; amount: bigint; }
  export interface LoyaltyPot { version: number; bump: number; mint: PublicKey; slot: number; epoch: number; payable: bigint; claimed: bigint; eligibleSupply: bigint; }
  export interface LoyaltyRolled { mint: PublicKey; epoch: number; payable: bigint; eligibleSupply: bigint; }
  export interface Manifest { kind: number; tokenFlags: number; poolFlags: number; maxCutBuyBps: number; maxCutSellBps: number; maxCutTransferBps: number; maxDiscountBps: number; mayRefuse: boolean; mayBurn: boolean; dataBytes: number; readsOtherPools: number; }
  export type Phase = 'Before' | 'After';
  export interface PoolHookArgs { op: PoolOp; phase: Phase; pool: PublicKey; baseMint: PublicKey; quoteMint: PublicKey; actor: PublicKey; recipient: PublicKey; direction: number; amountIn: bigint; amountOut: bigint; baseReserve: bigint; quoteReserve: bigint; virtualBase: bigint; virtualQuote: bigint; lpFeeBps: number; protocolFeeBps: number; swapCount: bigint; createdAt: bigint; lpAmount: bigint; hookData: Buffer; route: RouteContext; }
  export type PoolOp = 'Initialize' | 'AddLiquidity' | 'RemoveLiquidity' | 'Swap';
  export interface ProtocolFee { source: number; mint: PublicKey; amount: bigint; reference: Buffer; ts: bigint; }
  export interface RaidMarked { mint: PublicKey; rival: PublicKey; trader: PublicKey; volume: bigint; points: number; lootTicket: boolean; }
  export interface ReferralPaid { mint: PublicKey; buyer: PublicKey; referrer: PublicKey; gross: bigint; paid: bigint; bounty: bigint; }
  export interface Referred { version: number; bump: number; mint: PublicKey; buyer: PublicKey; referrer: PublicKey; owed: bigint; paid: bigint; }
  export interface RouteContext { routeInputMint: PublicKey; routeOutputMint: PublicKey; firstPool: PublicKey; routeAmountIn: bigint; hopIndex: number; hopCount: number; }
  export interface ShieldTaken { mint: PublicKey; owner: PublicKey; cut: bigint; }
  export interface TokenSlotArgs { op: TokenSlotOp; phase: Phase; slot: number; item: PublicKey; mint: PublicKey; source: PublicKey; destination: PublicKey; sourceOwner: PublicKey; destinationOwner: PublicKey; authority: PublicKey; authorityIsDelegate: boolean; amount: bigint; delta: bigint; totalDelta: bigint; sourceBalance: bigint; destinationBalance: bigint; decimals: number; supply: bigint; sourceData: Buffer; destinationData: Buffer; payload: Buffer; }
  export type TokenSlotOp = 'Transfer' | 'Burn' | 'Touch';
}

export namespace War {
  export interface BountyClaimed { mint: PublicKey; owner: PublicKey; points: number; paid: bigint; }
  export interface CandidateChallenged { season: number; mint: PublicKey; score: bigint; submittedBy: PublicKey; beaten: PublicKey; }
  export interface CandidateSubmitted { season: number; mint: PublicKey; score: bigint; submittedBy: PublicKey; }
  export interface Captured { rivalMint: PublicKey; amount: bigint; cost: bigint; capturedAt: bigint; razeWindowStart: bigint; razeWindowBase: bigint; razedInWindow: bigint; }
  export interface CapturedReturned { mint: PublicKey; rivalMint: PublicKey; amount: bigint; treatyItem: PublicKey; }
  export interface ConfigApplied { change: ConfigChange; eta: bigint; }
  export interface ConfigArgs { admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; params: WarParams; }
  export interface ConfigChange { admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; params: WarParams; }
  export interface ConfigProposed { change: ConfigChange; eta: bigint; }
  export interface CounterStrikeExecuted { mint: PublicKey; spent: bigint; burned: bigint; bounty: bigint; cranker: PublicKey; }
  export interface Launch { version: number; bump: number; mint: PublicKey; creator: PublicKey; pool: PublicKey; quoteMint: PublicKey; status: number; creatorFeeBps: number; lpFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; virtualQuote: bigint; virtualBase: bigint; graduationQuote: bigint; curveTokens: bigint; reserveTokens: bigint; reserveHolding: PublicKey; quoteHolding: PublicKey; lpHolding: PublicKey; createdAt: bigint; graduatedAt: bigint; creatorFeesAccrued: bigint; creatorFeesClaimed: bigint; graduationTopup: bigint; graduationBurned: bigint; rules: LaunchRules; modules: number; kitConfig: PublicKey; holderVault: PublicKey; kitCallerBump: number; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; creatorBought: boolean; holderFeesAccrued: bigint; burnedOnTrades: bigint; config: PublicKey; customHook: PublicKey | null; customHookFlags: number; authorShareBps: number; authorFeesPaid: bigint; slotLaunch: number; reserved: Buffer; }
  export interface LaunchRules { holderFeeBuyBps: number; holderFeeSellBps: number; burnBuyBps: number; burnSellBps: number; maxWalletBps: number; creatorLockSecs: number; earlyWindowSecs: number; earlyLockSecs: number; }
  export interface LootEntry { templateId: number; weight: number; ranges: (ParamRange)[]; }
  export interface LootTable { version: number; bump: number; season: number; count: number; entries: (LootEntry)[]; eta: bigint; }
  export interface LootTableProposed { season: number; eta: bigint; }
  export interface Mint { version: number; decimals: number; supply: bigint; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; createdAt: bigint; creator: PublicKey; hookSignerBump: number; reserved: Buffer; slotAuthority: PublicKey | null; slotCount: number; slots: (Slot)[]; }
  export interface ParamRange { min: number; max: number; }
  export interface PendingCancelled { what: number; season: number; eta: bigint; }
  export interface PendingConfig { admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; params: WarParams; eta: bigint; }
  export interface PrizePaid { season: number; winner: PublicKey | null; toWinner: bigint; toTreasury: bigint; bounty: bigint; cranker: PublicKey; }
  export interface QuestClaimed { questId: number; mint: PublicKey; owner: PublicKey; season: number; period: number; }
  export interface QuestMark { version: number; bump: number; season: number; mint: PublicKey; owner: PublicKey; lastPeriod: number; lastForgeCount: bigint; }
  export interface RazeWaited { mint: PublicKey; rivalMint: PublicKey; rivalPrice: bigint; rivalTwap: bigint; }
  export interface Razed { mint: PublicKey; rivalMint: PublicKey; sold: bigint; got: bigint; bounty: bigint; cranker: PublicKey; capturedLeft: bigint; }
  export interface RollCancelled { roll: PublicKey; mint: PublicKey; owner: PublicKey; }
  export interface RollRequest { version: number; bump: number; owner: PublicKey; mint: PublicKey; holding: PublicKey; nonce: bigint; season: number; requestedSlot: bigint; requestedAt: bigint; oracleProgram: PublicKey; oracleAccount: PublicKey; }
  export interface RollRequested { roll: PublicKey; mint: PublicKey; owner: PublicKey; holding: PublicKey; season: number; requestedSlot: bigint; oracleProgram: PublicKey; oracleAccount: PublicKey; }
  export interface RollRevealed { roll: PublicKey; mint: PublicKey; owner: PublicKey; item: PublicKey; templateId: number; params: (number)[]; season: number; }
  export interface ScoreWeights { raidVolumeWon: bigint; sieges: bigint; siegeSpend: bigint; timesBesieged: bigint; counterStrikes: bigint; treatySecs: bigint; }
  export interface Season { version: number; bump: number; number: number; startsAt: bigint; endsAt: bigint; weights: ScoreWeights; penalizeBesieged: boolean; eta: bigint; opened: boolean; leader: PublicKey | null; leaderScore: bigint; finalized: boolean; prizePaid: bigint; reserved: Buffer; }
  export interface SeasonArgs { number: number; startsAt: bigint; weights: ScoreWeights; penalizeBesieged: boolean; }
  export interface SeasonCounters { raidVolumeWon: bigint; sieges: number; siegeSpend: bigint; timesBesieged: number; counterStrikes: number; treatySecs: bigint; funded: bigint; }
  export interface SeasonFinalized { season: number; winner: PublicKey | null; score: bigint; }
  export interface SeasonOpened { season: number; startsAt: bigint; endsAt: bigint; }
  export interface SeasonProposed { season: number; startsAt: bigint; endsAt: bigint; weights: ScoreWeights; penalizeBesieged: boolean; eta: bigint; }
  export interface SiegeExecuted { mint: PublicKey; rivalMint: PublicKey; spent: bigint; bought: bigint; bounty: bigint; cranker: PublicKey; capturedTotal: bigint; }
  export interface SiegeWaited { mint: PublicKey; rivalMint: PublicKey; rivalPrice: bigint; rivalTwap: bigint; }
  export interface SliceArgs { first: number; second: number; }
  export interface Slot { kind: number; equipRule: number; bounds: SlotBounds; dataOffset: number; dataLen: number; item: PublicKey; program: PublicKey; flags: number; poolFlags: number; equipVault: PublicKey; signerBump: number; launchSignerBump: number; dataEpoch: number; extraCount: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface TreatyInflowShared { mint: PublicKey; amount: bigint; bounty: bigint; cranker: PublicKey; }
  export interface TreatyTimeAccrued { mint: PublicKey; treatyItem: PublicKey; secs: bigint; season: number; }
  export interface WarChestCreated { mint: PublicKey; chest: PublicKey; treatyInbox: PublicKey; warState: PublicKey; }
  export interface WarConfig { version: number; bump: number; prizeVaultBump: number; admin: PublicKey; protocolTreasury: PublicKey; randomnessProgram: PublicKey; treatyTemplateId: number | null; currentSeason: number; lastWinner: PublicKey | null; lastWinnerSeason: number; params: WarParams; pending: PendingConfig | null; reserved: Buffer; }
  export interface WarFunded { mint: PublicKey; amount: bigint; balance: bigint; fundedTotal: bigint; }
  export interface WarParams { adminTimelockSecs: bigint; maxCrankBountyBps: number; siegeIntervalSecs: bigint; siegeMaxSpendBps: number; siegeMaxPremiumBps: number; siegeSlippageBps: number; siegeUnitLamports: bigint; counterMaxSpendBps: number; counterMinIntervalSecs: bigint; razeMaxBpsPerInterval: number; razeIntervalSecs: bigint; bountyMaxPerClaim: bigint; minTwapSecs: bigint; raidWindowSecs: bigint; rollExpirySecs: bigint; questPeriodSecs: bigint; questRaidPoints: number; seasonSecs: bigint; challengeSecs: bigint; seasonPrizeShareBps: number; pointUnitLamports: bigint; lootMinRaidLamports: bigint; razeMaxDiscountBps: number; bountyMaxPointBps: number; raidVolumePerFunded: bigint; }
  export interface WarState { version: number; bump: number; chestBump: number; inboxBump: number; mint: PublicKey; launch: PublicKey; lastSeenBalance: bigint; fundedTotal: bigint; spentSiege: bigint; spentCounter: bigint; paidBounties: bigint; paidCranks: bigint; razedProceeds: bigint; treatySharedTotal: bigint; lastSiegeAt: bigint; lastCounterAt: bigint; lastTreatyTick: bigint; underSiegeUntil: bigint; siegeByChest: PublicKey; captured: (Captured)[]; seasonId: number; season: SeasonCounters; prevSeason: SeasonCounters; reserved: Buffer; }
}

export namespace Kit {
  export interface Delta { amount: bigint; account: number; }
  export interface Holding { version: number; bump: number; mint: PublicKey; owner: PublicKey; amount: bigint; delegate: PublicKey | null; delegatedAmount: bigint; frozen: boolean; hookData: Buffer; voteLocked: bigint; voteLockUntil: bigint; }
  export interface HookReturn { deltas: (Delta)[]; burn: bigint; lpFeeBps: number | null; sourceHookData: Buffer | null; destinationHookData: Buffer | null; }
  export interface KitConfig { version: number; bump: number; kitCallerBump: number; modules: number; graduated: boolean; eligible: bigint; minEligible: bigint; mint: PublicKey; launch: PublicKey; pool: PublicKey; creator: PublicKey; rewardMint: PublicKey; rewardVault: PublicKey; supplyAtInit: bigint; maxWalletBps: number; maxWalletAmount: bigint; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; accPerShare: bigint; rem: bigint; held: bigint; seen: bigint; streamRemaining: bigint; streamLast: bigint; streamEnd: bigint; totalDistributed: bigint; totalClaimed: bigint; totalShared: bigint; createdAt: bigint; streamNext: bigint; creatorIsCompanion: boolean; reserved: Buffer; }
  export interface KitGraduated { mint: PublicKey; ts: bigint; }
  export interface KitInitArgs { launch: PublicKey; pool: PublicKey; creator: PublicKey; rewardMint: PublicKey; modules: number; maxWalletBps: number; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; kitCallerBump: number; }
  export interface KitInstalled { mint: PublicKey; kitConfig: PublicKey; launch: PublicKey; pool: PublicKey; creator: PublicKey; rewardMint: PublicKey; rewardVault: PublicKey; modules: number; supply: bigint; minEligible: bigint; maxWalletBps: number; maxWalletAmount: bigint; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; ts: bigint; }
  export interface Mint { version: number; decimals: number; supply: bigint; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; createdAt: bigint; creator: PublicKey; hookSignerBump: number; reserved: Buffer; slotAuthority: PublicKey | null; slotCount: number; slots: (Slot)[]; }
  export type Phase = 'Before' | 'After';
  export interface RewardsClaimed { mint: PublicKey; owner: PublicKey; amount: bigint; owedLeft: bigint; totalClaimed: bigint; }
  export interface RewardsShared { mint: PublicKey; from: PublicKey; amount: bigint; totalShared: bigint; }
  export interface Slot { kind: number; equipRule: number; bounds: SlotBounds; dataOffset: number; dataLen: number; item: PublicKey; program: PublicKey; flags: number; poolFlags: number; equipVault: PublicKey; signerBump: number; launchSignerBump: number; dataEpoch: number; extraCount: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface TokenHookArgs { op: TokenOp; phase: Phase; mint: PublicKey; source: PublicKey; destination: PublicKey; sourceOwner: PublicKey; destinationOwner: PublicKey; authority: PublicKey; authorityIsDelegate: boolean; amount: bigint; delta: bigint; sourceBalance: bigint; destinationBalance: bigint; decimals: number; supply: bigint; sourceHookData: Buffer; destinationHookData: Buffer; }
  export type TokenOp = 'Transfer' | 'Mint' | 'Burn';
}

export namespace Companion {
  export interface BeneficiaryPaid { companion: PublicKey; lamports: bigint; }
  export interface BoughtBack { companion: PublicKey; spent: bigint; burned: bigint; bounty: bigint; cranker: PublicKey; }
  export interface BuybackWaited { companion: PublicKey; price: bigint; reference: bigint; }
  export interface Companion { version: number; bump: number; creatorBump: number; mint: PublicKey; beneficiary: PublicKey; split: Split; bountyBps: number; maxBuyback: bigint; buybackInterval: bigint; vestSecs: bigint; launched: boolean; launchedAt: bigint; devTokens: bigint; devReleased: bigint; pendingBuyback: bigint; pendingHolders: bigint; pendingBeneficiary: bigint; lastBuybackAt: bigint; claimedTotal: bigint; spentTotal: bigint; burnedTotal: bigint; sharedTotal: bigint; paidBeneficiaryTotal: bigint; bountiesTotal: bigint; referencePrice: bigint; referenceAt: bigint; warTotal: bigint; reserved: Buffer; }
  export interface CompanionCreated { companion: PublicKey; mint: PublicKey; creator: PublicKey; beneficiary: PublicKey; split: Split; bountyBps: number; maxBuyback: bigint; buybackInterval: bigint; vestSecs: bigint; }
  export interface CompanionLaunched { companion: PublicKey; mint: PublicKey; ts: bigint; }
  export interface CompanionWarFunded { companion: PublicKey; mint: PublicKey; warChest: PublicKey; amount: bigint; warTotal: bigint; }
  export interface CreateArgs { split: Split; bountyBps: number; maxBuyback: bigint; buybackInterval: bigint; vestSecs: bigint; fund: bigint; }
  export interface CreateLaunchArgs { name: string; symbol: string; uri: string; creatorFeeBps: number; virtualQuote: bigint; rules: LaunchRules; }
  export interface DevBought { companion: PublicKey; lamports: bigint; tokens: bigint; devTokens: bigint; }
  export interface DevReleased { companion: PublicKey; tokens: bigint; released: bigint; }
  export interface FeesClaimed { companion: PublicKey; claimed: bigint; bounty: bigint; toBuyback: bigint; toHolders: bigint; toBeneficiary: bigint; cranker: PublicKey; }
  export interface Launch { version: number; bump: number; mint: PublicKey; creator: PublicKey; pool: PublicKey; quoteMint: PublicKey; status: number; creatorFeeBps: number; lpFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; virtualQuote: bigint; virtualBase: bigint; graduationQuote: bigint; curveTokens: bigint; reserveTokens: bigint; reserveHolding: PublicKey; quoteHolding: PublicKey; lpHolding: PublicKey; createdAt: bigint; graduatedAt: bigint; creatorFeesAccrued: bigint; creatorFeesClaimed: bigint; graduationTopup: bigint; graduationBurned: bigint; rules: LaunchRules; modules: number; kitConfig: PublicKey; holderVault: PublicKey; kitCallerBump: number; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; creatorBought: boolean; holderFeesAccrued: bigint; burnedOnTrades: bigint; config: PublicKey; customHook: PublicKey | null; customHookFlags: number; authorShareBps: number; authorFeesPaid: bigint; slotLaunch: number; reserved: Buffer; }
  export interface LaunchRules { holderFeeBuyBps: number; holderFeeSellBps: number; burnBuyBps: number; burnSellBps: number; maxWalletBps: number; creatorLockSecs: number; earlyWindowSecs: number; earlyLockSecs: number; }
  export interface SharedWithHolders { companion: PublicKey; amount: bigint; bounty: bigint; cranker: PublicKey; }
  export interface Split { buybackBps: number; holdersBps: number; beneficiaryBps: number; warBps: number; }
}

export namespace Launch {
  export interface AuthorFeesPaid { launch: PublicKey; mint: PublicKey; config: PublicKey; author: PublicKey; amount: bigint; paidTotal: bigint; slot: bigint; ts: bigint; }
  export interface Config { version: number; bump: number; admin: PublicKey; treasury: PublicKey; quoteMint: PublicKey; launchFeeLamports: bigint; lpFeeBps: number; maxCreatorFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; curveBps: number; supply: bigint; decimals: number; minVirtualQuote: bigint; maxVirtualQuote: bigint; paused: boolean; launches: bigint; ruleBounds: RuleBounds; reserved: Buffer; }
  export interface ConfigArgs { admin: PublicKey; treasury: PublicKey; quoteMint: PublicKey; launchFeeLamports: bigint; lpFeeBps: number; maxCreatorFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; curveBps: number; supply: bigint; decimals: number; minVirtualQuote: bigint; maxVirtualQuote: bigint; paused: boolean; ruleBounds: RuleBounds; }
  export interface ConfigListed { config: PublicKey; author: PublicKey; authorShareBps: number; ts: bigint; }
  export interface ConfigSet { admin: PublicKey; treasury: PublicKey; quoteMint: PublicKey; launchFeeLamports: bigint; lpFeeBps: number; maxCreatorFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; curveBps: number; supply: bigint; decimals: number; minVirtualQuote: bigint; maxVirtualQuote: bigint; paused: boolean; ruleBounds: RuleBounds; ts: bigint; }
  export interface CreateConfigArgs { rules: LaunchRules; creatorFeeBps: number; customHook: PublicKey | null; customHookFlags: number; label: string; }
  export interface CreateLaunchArgs { name: string; symbol: string; uri: string; creatorFeeBps: number; virtualQuote: bigint; rules: LaunchRules; }
  export interface CreatorFeesClaimed { launch: PublicKey; mint: PublicKey; creator: PublicKey; amount: bigint; claimedTotal: bigint; slot: bigint; ts: bigint; }
  export interface Delta { amount: bigint; account: number; }
  export interface Graduated { launch: PublicKey; mint: PublicKey; pool: PublicKey; cranker: PublicKey; topup: bigint; burned: bigint; baseReserve: bigint; quoteReserve: bigint; lpMinted: bigint; supply: bigint; slot: bigint; ts: bigint; }
  export interface HookReturn { deltas: (Delta)[]; burn: bigint; lpFeeBps: number | null; sourceHookData: Buffer | null; destinationHookData: Buffer | null; }
  export interface Launch { version: number; bump: number; mint: PublicKey; creator: PublicKey; pool: PublicKey; quoteMint: PublicKey; status: number; creatorFeeBps: number; lpFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; virtualQuote: bigint; virtualBase: bigint; graduationQuote: bigint; curveTokens: bigint; reserveTokens: bigint; reserveHolding: PublicKey; quoteHolding: PublicKey; lpHolding: PublicKey; createdAt: bigint; graduatedAt: bigint; creatorFeesAccrued: bigint; creatorFeesClaimed: bigint; graduationTopup: bigint; graduationBurned: bigint; rules: LaunchRules; modules: number; kitConfig: PublicKey; holderVault: PublicKey; kitCallerBump: number; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; creatorBought: boolean; holderFeesAccrued: bigint; burnedOnTrades: bigint; config: PublicKey; customHook: PublicKey | null; customHookFlags: number; authorShareBps: number; authorFeesPaid: bigint; slotLaunch: number; reserved: Buffer; }
  export interface LaunchConfig { version: number; creator: PublicKey; rules: LaunchRules; creatorFeeBps: number; customHook: PublicKey | null; customHookFlags: number; label: string; createdAt: bigint; authorShareBps: number; reserved: Buffer; }
  export interface LaunchConfigCreated { config: PublicKey; creator: PublicKey; rules: LaunchRules; creatorFeeBps: number; customHook: PublicKey | null; customHookFlags: number; label: string; ts: bigint; }
  export interface LaunchCreated { launch: PublicKey; mint: PublicKey; creator: PublicKey; pool: PublicKey; quoteMint: PublicKey; lpMint: PublicKey; name: string; symbol: string; uri: string; supply: bigint; decimals: number; creatorFeeBps: number; lpFeeBps: number; sniperWindowSecs: bigint; sniperStartBps: number; virtualQuote: bigint; virtualBase: bigint; graduationQuote: bigint; curveTokens: bigint; reserveTokens: bigint; launchFeeLamports: bigint; rules: LaunchRules; modules: number; kitConfig: PublicKey | null; holderVault: PublicKey | null; creatorUnlockAt: bigint; earlyWindowEnd: bigint; earlyUnlockAt: bigint; config: PublicKey | null; customHook: PublicKey | null; customHookFlags: number; slot: bigint; ts: bigint; }
  export interface LaunchPrepared { mint: PublicKey; creator: PublicKey; slotCount: number; kitSlot: boolean; slot: bigint; ts: bigint; }
  export interface LaunchRules { holderFeeBuyBps: number; holderFeeSellBps: number; burnBuyBps: number; burnSellBps: number; maxWalletBps: number; creatorLockSecs: number; earlyWindowSecs: number; earlyLockSecs: number; }
  export type Phase = 'Before' | 'After';
  export interface PoolHookArgs { op: PoolOp; phase: Phase; pool: PublicKey; baseMint: PublicKey; quoteMint: PublicKey; actor: PublicKey; recipient: PublicKey; direction: number; amountIn: bigint; amountOut: bigint; baseReserve: bigint; quoteReserve: bigint; virtualBase: bigint; virtualQuote: bigint; lpFeeBps: number; protocolFeeBps: number; swapCount: bigint; createdAt: bigint; lpAmount: bigint; hookData: Buffer; route: RouteContext; }
  export interface PoolItemCuts { launch: PublicKey; pool: PublicKey; mint: PublicKey; side: number; discountBps: number; parts: (PoolItemPart)[]; poolCutsDelta: bigint; burned: bigint; slot: bigint; ts: bigint; }
  export interface PoolItemPart { slot: number; item: PublicKey; discountBps: number; cut: bigint; burn: bigint; }
  export type PoolOp = 'Initialize' | 'AddLiquidity' | 'RemoveLiquidity' | 'Swap';
  export interface PoolRegistryRefreshed { mint: PublicKey; pool: PublicKey; items: (PublicKey)[]; accounts: number; ts: bigint; }
  export interface PrepareLaunchArgs { name: string; symbol: string; uri: string; creatorFeeBps: number; rules: LaunchRules; slots: (SlotInit)[]; }
  export interface PreparedLaunch { version: number; bump: number; mint: PublicKey; creator: PublicKey; rules: LaunchRules; creatorFeeBps: number; slotCount: number; preparedAt: bigint; launched: boolean; reserved: Buffer; }
  export interface RouteContext { routeInputMint: PublicKey; routeOutputMint: PublicKey; firstPool: PublicKey; routeAmountIn: bigint; hopIndex: number; hopCount: number; }
  export interface RuleBounds { maxHolderFeeBps: number; maxBurnBps: number; maxRulesFeeBps: number; minMaxWalletBps: number; maxMaxWalletBps: number; maxCreatorLockSecs: number; maxEarlyWindowSecs: number; maxEarlyLockSecs: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface SlotInit { kind: number; equipRule: number; bounds: SlotBounds; dataLen: number; lockedProgram: PublicKey | null; lockedFlags: number; lockedExtraCount: number; }
}

export namespace Swap {
  export interface AddLiquidityArgs { baseDesired: bigint; quoteDesired: bigint; minLp: bigint; baseHookAccounts: number; quoteHookAccounts: number; hookData: Buffer; }
  export interface Config { version: number; bump: number; admin: PublicKey; protocolFeeBps: number; feeCollector: PublicKey; treasury: PublicKey; poolCreationFeeLamports: bigint; paused: boolean; poolsCreated: bigint; launchProtocolShareBps: number; reserved: Buffer; }
  export interface ConfigArgs { admin: PublicKey; protocolFeeBps: number; feeCollector: PublicKey; treasury: PublicKey; poolCreationFeeLamports: bigint; paused: boolean; launchProtocolShareBps: number; }
  export interface ConfigSet { admin: PublicKey; protocolFeeBps: number; launchProtocolShareBps: number; feeCollector: PublicKey; treasury: PublicKey; poolCreationFeeLamports: bigint; paused: boolean; ts: bigint; }
  export interface CreatePoolArgs { lpFeeBps: number; hookProgram: PublicKey; hookFlags: number; virtualBase: bigint; virtualQuote: bigint; baseAmount: bigint; quoteAmount: bigint; baseHookAccounts: number; quoteHookAccounts: number; hookData: Buffer; }
  export interface CurveFinalized { pool: PublicKey; baseReserve: bigint; quoteReserve: bigint; lpSupply: bigint; lpMinted: bigint; lpRecipient: PublicKey; slot: bigint; ts: bigint; }
  export interface DeltaPaid { holding: PublicKey; amount: bigint; }
  export interface HopArgs { direction: number; accounts: number; inHookAccounts: number; outHookAccounts: number; }
  export interface LiquidityAdded { pool: PublicKey; provider: PublicKey; baseAmount: bigint; quoteAmount: bigint; lpMinted: bigint; baseReserve: bigint; quoteReserve: bigint; lpSupply: bigint; slot: bigint; ts: bigint; }
  export interface LiquidityRemoved { pool: PublicKey; provider: PublicKey; baseAmount: bigint; quoteAmount: bigint; lpBurned: bigint; baseReserve: bigint; quoteReserve: bigint; lpSupply: bigint; slot: bigint; ts: bigint; }
  export interface Mint { version: number; decimals: number; supply: bigint; maxSupply: bigint; mintAuthority: PublicKey | null; freezeAuthority: PublicKey | null; hookAuthority: PublicKey | null; metadataAuthority: PublicKey | null; hookProgram: PublicKey | null; hookFlags: number; name: string; symbol: string; uri: string; createdAt: bigint; creator: PublicKey; hookSignerBump: number; reserved: Buffer; slotAuthority: PublicKey | null; slotCount: number; slots: (Slot)[]; }
  export interface Pool { version: number; bump: number; lpMintBump: number; baseMint: PublicKey; quoteMint: PublicKey; lpMint: PublicKey; baseVault: PublicKey; quoteVault: PublicKey; hookProgram: PublicKey | null; hookFlags: number; lpFeeBps: number; protocolFeeBps: number; baseReserve: bigint; quoteReserve: bigint; virtualBase: bigint; virtualQuote: bigint; lpSupply: bigint; protocolFeesQuote: bigint; curve: boolean; creator: PublicKey; createdAt: bigint; lastSwapAt: bigint; swapCount: bigint; baseVolume: bigint; quoteVolume: bigint; hookSignerBump: number; feeModel: number; protocolShareBps: number; reserved: Buffer; }
  export interface PoolCreated { pool: PublicKey; payer: PublicKey; creator: PublicKey; baseMint: PublicKey; quoteMint: PublicKey; lpMint: PublicKey; baseVault: PublicKey; quoteVault: PublicKey; lpFeeBps: number; protocolFeeBps: number; feeModel: number; protocolShareBps: number; hookProgram: PublicKey | null; hookFlags: number; virtualBase: bigint; virtualQuote: bigint; baseReserve: bigint; quoteReserve: bigint; lpSupply: bigint; lpMinted: bigint; curve: boolean; slot: bigint; ts: bigint; }
  export interface ProtocolFeesCollected { pool: PublicKey; quoteAmount: bigint; collector: PublicKey; ts: bigint; }
  export interface RemoveLiquidityArgs { lpAmount: bigint; minBase: bigint; minQuote: bigint; baseHookAccounts: number; quoteHookAccounts: number; hookData: Buffer; }
  export interface RouteContext { routeInputMint: PublicKey; routeOutputMint: PublicKey; firstPool: PublicKey; routeAmountIn: bigint; hopIndex: number; hopCount: number; }
  export interface RouteSwapped { trader: PublicKey; routeInputMint: PublicKey; routeOutputMint: PublicKey; amountIn: bigint; amountOut: bigint; pools: (PublicKey)[]; slot: bigint; ts: bigint; }
  export interface Slot { kind: number; equipRule: number; bounds: SlotBounds; dataOffset: number; dataLen: number; item: PublicKey; program: PublicKey; flags: number; poolFlags: number; equipVault: PublicKey; signerBump: number; launchSignerBump: number; dataEpoch: number; extraCount: number; }
  export interface SlotBounds { maxCutBps: number; mayRefuse: boolean; mayWriteData: boolean; mayAnswerTouch: boolean; mayBurn: boolean; }
  export interface SwapArgs { direction: number; amountIn: bigint; minAmountOut: bigint; inHookAccounts: number; outHookAccounts: number; hookData: Buffer; }
  export interface SwapRouteArgs { amountIn: bigint; minAmountOut: bigint; hops: (HopArgs)[]; hookData: Buffer; }
  export interface Swapped { pool: PublicKey; trader: PublicKey; recipient: PublicKey; direction: number; amountIn: bigint; deltasIn: (DeltaPaid)[]; burnIn: bigint; cutsIn: bigint; receivedIn: bigint; lpFee: bigint; protocolFee: bigint; lpFeeBps: number; amountOut: bigint; deltasOut: (DeltaPaid)[]; burnOut: bigint; cutsOut: bigint; deliveredOut: bigint; baseReserve: bigint; quoteReserve: bigint; virtualBase: bigint; virtualQuote: bigint; swapCount: bigint; slot: bigint; ts: bigint; route: RouteContext; }
}

export namespace Agents {
  export interface AgentCredited { passport: PublicKey; kind: number; value: bigint; ts: bigint; }
  export interface AgentKey { passport: PublicKey; bump: number; }
  export interface AgentKeyRotated { passport: PublicKey; oldKey: PublicKey; newKey: PublicKey; badgeMint: PublicKey; generation: number; ts: bigint; }
  export interface AgentsConfig { version: number; bump: number; signerBump: number; admin: PublicKey; feeCollector: PublicKey; soulboundItem: PublicKey; params: AgentsParams; verifiers: (PublicKey)[]; targets: (PublicKey)[]; pending: ConfigChange | null; passports: bigint; reserved: Buffer; }
  export interface AgentsParams { nameMaxLen: number; uriMaxLen: number; handleMaxLen: number; passportFeeLamports: bigint; maxPassportsPerOperator: number; attestQuorum: number; attestMaxTtlSecs: bigint; policyDaySecs: bigint; bondLamports: bigint; bondMinPassportAgeSecs: bigint; bondCancelGraceSecs: bigint; treatyHoldSecs: bigint; adminTimelockSecs: bigint; }
  export interface ArmoryConfig { version: number; bump: number; admin: PublicKey; pendingAdmin: PublicKey | null; pendingAdminAt: bigint; itemsMinted: bigint; templates: number; params: ArmoryParams; itemProtocolBps: number; reserved: Buffer; }
  export interface ArmoryParams { maxRoyaltyBps: number; votePeriodSecs: number; voteQuorumBps: number; minNoticeSecs: number; maxNoticeSecs: number; forgeGainBps: number; minTwapSecs: number; maxPoolItemCutBps: number; maxPoolItemDiscountBps: number; maxItemReads: number; adminTimelockSecs: number; settleBountyBps: number; proposalMinBps: number; }
  export interface AttestArgs { teeKind: number; measurement: Buffer; reportData: Buffer; nonce: Buffer; quoteHash: Buffer; quoteUri: string; sourceUri: string; expiresAt: bigint; }
  export interface Attestation { passport: PublicKey; agentKey: PublicKey; teeKind: number; measurement: Buffer; reportData: Buffer; nonce: Buffer; quoteHash: Buffer; quoteUri: string; sourceUri: string; submittedAt: bigint; expiresAt: bigint; endorsements: number; round: number; bump: number; }
  export interface AttestationEndorsed { passport: PublicKey; verifier: PublicKey; quoteHash: Buffer; endorsements: number; ts: bigint; }
  export interface AttestationSubmitted { passport: PublicKey; teeKind: number; measurement: Buffer; quoteHash: Buffer; expiresAt: bigint; round: number; ts: bigint; }
  export interface BadgeIssued { passport: PublicKey; badgeMint: PublicKey; agentKey: PublicKey; generation: number; ts: bigint; }
  export interface Bond { passport: PublicKey; proposalA: PublicKey; proposalB: PublicKey; mintA: PublicKey; mintB: PublicKey; treatyItem: PublicKey; amount: bigint; postedAt: bigint; ratifiedAt: bigint; status: number; bump: number; }
  export interface BondForfeited { bond: PublicKey; passport: PublicKey; inboxA: PublicKey; inboxB: PublicKey; amount: bigint; ts: bigint; }
  export interface BondMark { bond: PublicKey; bump: number; }
  export interface BondPosted { bond: PublicKey; passport: PublicKey; proposalA: PublicKey; proposalB: PublicKey; treatyItem: PublicKey; amount: bigint; ts: bigint; }
  export interface BondReturned { bond: PublicKey; passport: PublicKey; ratified: boolean; amount: bigint; ts: bigint; }
  export interface Commitment { passport: PublicKey; reference: Buffer; hash: Buffer; committedAt: bigint; bump: number; }
  export interface Committed { passport: PublicKey; reference: Buffer; hash: Buffer; ts: bigint; }
  export interface ConfigArgs { admin: PublicKey; feeCollector: PublicKey; soulboundItem: PublicKey; params: AgentsParams; verifiers: (PublicKey)[]; targets: (PublicKey)[]; }
  export interface ConfigChange { admin: PublicKey; feeCollector: PublicKey; soulboundItem: PublicKey; params: AgentsParams; verifiers: (PublicKey)[]; targets: (PublicKey)[]; eta: bigint; }
  export interface ConfigInitialized { admin: PublicKey; feeCollector: PublicKey; params: AgentsParams; ts: bigint; }
  export interface Directive { passport: PublicKey; seq: number; memoHash: Buffer; constraints: DirectiveConstraints; postedAt: bigint; supersededBy: number | null; bump: number; }
  export interface DirectiveConstraints { maxSpendPerAction: bigint; maxSpendPerDay: bigint; allowedTargets: (PublicKey)[]; allowedAccessModes: number; maxLicencePrice: bigint; frozen: boolean; }
  export interface DirectiveSet { passport: PublicKey; seq: number; memoHash: Buffer; ts: bigint; }
  export interface Endorsement { attestation: PublicKey; verifier: PublicKey; quoteHash: Buffer; round: number; endorsedAt: bigint; bump: number; }
  export interface EndorsementRevoked { passport: PublicKey; verifier: PublicKey; endorsements: number; ts: bigint; }
  export interface EquipConfig { targets: (PublicKey)[]; role: number; }
  export interface Item { version: number; bump: number; itemMint: PublicKey; templateId: number; params: (number)[]; manifest: Manifest; author: PublicKey; royaltyBps: number; level: number; source: number; equippedCount: number; royaltyOwnerBump: number; createdAt: bigint; hasWear: boolean; reserved: Buffer; }
  export interface Link { passport: PublicKey; platform: number; handle: string; postUri: string; statementHash: Buffer; linkedAt: bigint; bump: number; }
  export interface LinkAdded { passport: PublicKey; platform: number; handle: string; postUri: string; statementHash: Buffer; ts: bigint; }
  export interface LinkRemoved { passport: PublicKey; platform: number; ts: bigint; }
  export interface Manifest { kind: number; tokenFlags: number; poolFlags: number; maxCutBuyBps: number; maxCutSellBps: number; maxCutTransferBps: number; maxDiscountBps: number; mayRefuse: boolean; mayBurn: boolean; dataBytes: number; readsOtherPools: number; }
  export interface MemoConfig { bump: number; params: MemoParams; pending: MemoParams | null; pendingEta: bigint; }
  export interface MemoParams { memoMaxBytes: number; postageLamports: bigint; minProof: number; }
  export interface MemoParamsProposed { eta: bigint; }
  export interface MessagePosted { passport: PublicKey; reference: Buffer; postage: bigint; ts: bigint; }
  export interface OperatorIndex { operator: PublicKey; next: number; active: number; bump: number; }
  export interface ParamsApplied { change: ConfigChange; ts: bigint; }
  export interface ParamsCancelled { ts: bigint; }
  export interface ParamsProposed { change: ConfigChange; ts: bigint; }
  export interface Passport { version: number; bump: number; operator: PublicKey; index: number; agentKey: PublicKey; name: string; avatarUri: string; bioUri: string; hireUri: string; kinds: number; status: number; proof: number; links: number; attestedUntil: bigint; badgeMint: PublicKey; badgeGeneration: number; badgeIssued: boolean; creditAgentId: Buffer | null; createdAt: bigint; lastActiveAt: bigint; record: TrackRecord; reserved: Buffer; }
  export interface PassportRegistered { passport: PublicKey; operator: PublicKey; agentKey: PublicKey; name: string; kinds: number; badgeMint: PublicKey; ts: bigint; }
  export interface PassportStatus { passport: PublicKey; status: number; ts: bigint; }
  export interface Policy { passport: PublicKey; frozen: boolean; perActionLamports: bigint; perDayLamports: bigint; dayStart: bigint; spentToday: bigint; tracked: (TrackedMint)[]; targets: (PublicKey)[]; bump: number; vaultBump: number; }
  export interface PolicyLimits { perActionLamports: bigint; perDayLamports: bigint; tracked: (TrackedLimit)[]; targets: (PublicKey)[]; }
  export interface PolicySet { passport: PublicKey; perActionLamports: bigint; perDayLamports: bigint; frozen: boolean; ts: bigint; }
  export interface PolicySpend { passport: PublicKey; targetProgram: PublicKey; solOut: bigint; ts: bigint; }
  export interface PolicyWithdraw { passport: PublicKey; mint: PublicKey | null; amount: bigint; ts: bigint; }
  export interface ProfileArgs { name: string; avatarUri: string; bioUri: string; hireUri: string; kinds: number; creditAgentId: Buffer | null; }
  export interface ProfileUpdated { passport: PublicKey; name: string; kinds: number; ts: bigint; }
  export interface ProofChanged { passport: PublicKey; old: number; new: number; ts: bigint; }
  export interface Proposal { version: number; bump: number; mint: PublicKey; slot: number; nonce: bigint; proposer: PublicKey; item: PublicKey | null; config: EquipConfig; createdAt: bigint; voteEnd: bigint; executableAt: bigint; votesFor: bigint; votesAgainst: bigint; votersOpen: number; status: number; reserved: Buffer; }
  export interface TrackRecord { itemsAuthored: number; itemsEquipped: number; itemsForged: number; royaltyClaims: number; royaltiesClaimedSol: bigint; treatiesProposed: number; treatiesRatified: number; treatiesHeld: number; treatiesBroken: number; bondsForfeited: number; cranks: number; crankValueLamports: bigint; bountiesClaimedLamports: bigint; lootReveals: number; }
  export interface TrackedLimit { mint: PublicKey; perAction: bigint; perDay: bigint; }
  export interface TrackedMint { mint: PublicKey; perAction: bigint; perDay: bigint; spentToday: bigint; }
  export interface TreatyBroken { bond: PublicKey; passport: PublicKey; ts: bigint; }
  export interface TreatyHeld { bond: PublicKey; passport: PublicKey; ts: bigint; }
}

export namespace Market {
  export interface Collection { version: number; bump: number; id: number; name: string; curator: PublicKey; templateIds: (number)[]; createdAt: bigint; }
  export interface CollectionCreated { id: number; name: string; curator: PublicKey; templateIds: (number)[]; ts: bigint; }
  export interface Commission { version: number; bump: number; vaultBump: number; creator: PublicKey; tokenMint: PublicKey; slot: number; nonce: bigint; briefUri: string; bountyLamports: bigint; incumbent: PublicKey; opensAt: bigint; closesAt: bigint; state: number; winner: PublicKey | null; submissions: number; }
  export interface CommissionOpened { commission: PublicKey; creator: PublicKey; tokenMint: PublicKey; slot: number; bountyLamports: bigint; closesAt: bigint; briefUri: string; }
  export interface CommissionPaid { commission: PublicKey; item: PublicKey; submitter: PublicKey; bountyLamports: bigint; ts: bigint; }
  export interface CommissionRefunded { commission: PublicKey; creator: PublicKey; bountyLamports: bigint; ts: bigint; }
  export interface Delisted { itemMint: PublicKey; seller: PublicKey; ts: bigint; }
  export interface Lease { version: number; bump: number; lessor: PublicKey; item: PublicKey; itemMint: PublicKey; tokenMint: PublicKey; slot: number; rentBps: number; feeLamports: bigint; termSecs: number; startsAt: bigint; endsAt: bigint; state: number; }
  export interface LeaseEnded { item: PublicKey; tokenMint: PublicKey; slot: number; ts: bigint; }
  export interface LeaseOffered { item: PublicKey; lessor: PublicKey; tokenMint: PublicKey; slot: number; rentBps: number; feeLamports: bigint; termSecs: number; ts: bigint; }
  export interface LeaseStarted { item: PublicKey; payer: PublicKey; startsAt: bigint; endsAt: bigint; }
  export interface LeaseWithdrawn { item: PublicKey; ts: bigint; }
  export interface LicenceBought { item: PublicKey; tokenMint: PublicKey; payer: PublicKey; holder: PublicKey; price: bigint; protocol: bigint; author: bigint; toHolder: bigint; endsAt: bigint; renewal: boolean; reference: Buffer; ts: bigint; }
  export interface LicenceConfig { bump: number; params: LicenceParams; pending: LicenceParams | null; pendingAt: bigint; protocolFeesTotal: bigint; licencesSold: bigint; }
  export interface LicenceExpired { item: PublicKey; tokenMint: PublicKey; ts: bigint; }
  export interface LicenceOffer { bump: number; item: PublicKey; itemMint: PublicKey; setBy: PublicKey; priceLamports: bigint; termSecs: number; per: number; maxLive: number; exclusive: boolean; live: number; active: boolean; updatedAt: bigint; }
  export interface LicenceOfferSet { item: PublicKey; holder: PublicKey; priceLamports: bigint; termSecs: number; per: number; maxLive: number; exclusive: boolean; active: boolean; ts: bigint; }
  export interface LicenceParams { protocolBps: number; authorBps: number; minSecs: number; maxSecs: number; }
  export interface LicenceParamsProposed { readyAt: bigint; }
  export interface LicenceRevoked { item: PublicKey; tokenMint: PublicKey; refund: bigint; ts: bigint; }
  export interface License { bump: number; item: PublicKey; tokenMint: PublicKey; payer: PublicKey; pricePaid: bigint; startsAt: bigint; endsAt: bigint; revokedAt: bigint; per: number; counted: boolean; }
  export interface Listed { item: PublicKey; itemMint: PublicKey; seller: PublicKey; priceLamports: bigint; expiresAt: bigint; ts: bigint; }
  export interface Listing { version: number; bump: number; seller: PublicKey; item: PublicKey; itemMint: PublicKey; priceLamports: bigint; createdAt: bigint; expiresAt: bigint; }
  export interface ListingExpired { itemMint: PublicKey; seller: PublicKey; ts: bigint; }
  export interface MarketConfig { version: number; bump: number; admin: PublicKey; treasury: PublicKey; params: MarketParams; collections: number; reserved: Buffer; }
  export interface MarketParams { feeBps: number; authorResaleBps: number; collectionMaxTemplates: number; maxRentBps: number; leaseMinSecs: number; leaseMaxSecs: number; commissionMinLamports: bigint; commissionVoteSecs: number; adminTimelockSecs: number; }
  export interface MarketParamsApplied { ts: bigint; }
  export interface MarketParamsProposed { readyAt: bigint; }
  export interface PendingMarketParams { bump: number; params: MarketParams; treasury: PublicKey; readyAt: bigint; active: boolean; }
  export interface ProtocolFee { source: number; mint: PublicKey; amount: bigint; reference: Buffer; ts: bigint; }
  export interface Sold { item: PublicKey; itemMint: PublicKey; seller: PublicKey; buyer: PublicKey; price: bigint; fee: bigint; resale: bigint; ts: bigint; }
  export interface Submission { version: number; bump: number; commission: PublicKey; item: PublicKey; submitter: PublicKey; submittedAt: bigint; }
  export interface Submitted { commission: PublicKey; item: PublicKey; submitter: PublicKey; ts: bigint; }
}

export namespace Social {
  export interface BadgeAward { bump: number; badgeId: number; recipient: PublicKey; awardedAt: bigint; }
  export interface BadgeAwarded { id: number; recipient: PublicKey; claimant: PublicKey; ts: bigint; }
  export interface BadgeCreated { id: number; mint: PublicKey; name: string; criterion: Criterion; claimsOpenAt: bigint; }
  export interface BadgeType { version: number; bump: number; mintBump: number; id: number; mint: PublicKey; name: string; criterion: Criterion; claimsOpenAt: bigint; awarded: bigint; createdAt: bigint; }
  export type Criterion = ({ name: 'FirstSiege' } & { mint: PublicKey; }) | ({ name: 'RaidPoints' } & { mint: PublicKey; min: number; }) | ({ name: 'ForgeLevel' } & { minLevel: number; }) | ({ name: 'ItemsAuthored' } & { min: bigint; }) | ({ name: 'RoyaltiesClaimed' } & { minLamports: bigint; });
  export interface Guild { version: number; bump: number; treasuryBump: number; id: number; name: string; officers: (PublicKey)[]; threshold: number; officersVersion: number; actions: bigint; createdAt: bigint; }
  export interface GuildAction { version: number; bump: number; guildId: number; nonce: bigint; kind: GuildActionKind; approvals: number; officersVersion: number; proposedAt: bigint; eta: bigint; executed: boolean; }
  export interface GuildActionApproved { id: number; nonce: bigint; officer: PublicKey; }
  export interface GuildActionExecuted { id: number; nonce: bigint; kind: GuildActionKind; ts: bigint; }
  export type GuildActionKind = ({ name: 'SpendSol' } & { to: PublicKey; lamports: bigint; }) | ({ name: 'SpendToken' } & { mint: PublicKey; to: PublicKey; amount: bigint; }) | ({ name: 'SetOfficers' } & { officers: (PublicKey)[]; threshold: number; });
  export interface GuildActionProposed { id: number; nonce: bigint; kind: GuildActionKind; eta: bigint; }
  export interface GuildCreated { id: number; name: string; founder: PublicKey; ts: bigint; }
  export interface GuildDeposit { id: number; from: PublicKey; lamports: bigint; ts: bigint; }
  export interface PendingSocialParams { bump: number; params: SocialParams; readyAt: bigint; active: boolean; }
  export interface Profile { version: number; bump: number; wallet: PublicKey; counters: (bigint)[]; createdAt: bigint; updatedAt: bigint; reserved: Buffer; }
  export interface ProfileOpened { wallet: PublicKey; ts: bigint; }
  export interface SkillChange { skills: (SkillDef)[]; callers: (PublicKey)[]; eta: bigint; }
  export interface SkillDef { id: number; counter: number; thresholds: (bigint)[]; }
  export interface SkillTable { version: number; bump: number; skills: (SkillDef)[]; callers: (PublicKey)[]; pending: SkillChange | null; }
  export interface SkillsApplied { skills: number; callers: number; ts: bigint; }
  export interface SkillsProposed { eta: bigint; }
  export interface SocialConfig { version: number; bump: number; admin: PublicKey; params: SocialParams; badges: number; guilds: number; reserved: Buffer; }
  export interface SocialParams { guildMaxOfficers: number; guildTimelockSecs: number; adminTimelockSecs: number; }
  export interface SocialParamsProposed { readyAt: bigint; }
  export interface WalletRecorded { wallet: PublicKey; callerProgram: PublicKey; counter: number; value: bigint; total: bigint; ts: bigint; }
}

export namespace Craft {
  export interface CraftConfig { version: number; bump: number; admin: PublicKey; treasury: PublicKey; seasonPool: PublicKey; outputProgram: PublicKey; callers: (PublicKey)[]; params: CraftParams; seasonOrigin: bigint; protocolFeesTotal: bigint; reserved: Buffer; }
  export interface CraftParams { recipeProtocolBps: number; maxInputs: number; seasonSecs: number; adminTimelockSecs: number; }
  export interface CraftParamsProposed { readyAt: bigint; }
  export interface Crafted { recipe: number; crafter: PublicKey; templateId: number; fee: bigint; reference: Buffer; ts: bigint; }
  export interface DropRule { version: number; bump: number; source: number; materialId: number; perUnitNum: bigint; perUnitDen: bigint; effectiveAt: bigint; pending: DropTerms | null; pendingAt: bigint; }
  export interface DropRuleProposed { source: number; materialId: number; perUnitNum: bigint; perUnitDen: bigint; readyAt: bigint; }
  export interface DropTerms { materialId: number; perUnitNum: bigint; perUnitDen: bigint; }
  export interface Dropped { source: number; materialId: number; callerProgram: PublicKey; recipient: PublicKey; measured: bigint; amount: bigint; season: bigint; ts: bigint; }
  export interface ItemWorn { item: PublicKey; ts: bigint; }
  export interface Material { version: number; bump: number; id: number; mint: PublicKey; name: string; emissionCapPerSeason: bigint; emittedThisSeason: bigint; season: bigint; emittedTotal: bigint; burnedTotal: bigint; pendingCap: bigint; pendingCapAt: bigint; }
  export interface MaterialCapProposed { id: number; cap: bigint; readyAt: bigint; }
  export interface MaterialCreated { id: number; mint: PublicKey; emissionCapPerSeason: bigint; ts: bigint; }
  export interface PendingCraft { bump: number; treasury: PublicKey; seasonPool: PublicKey; outputProgram: PublicKey; callers: (PublicKey)[]; params: CraftParams; readyAt: bigint; active: boolean; }
  export interface ProtocolFee { source: number; mint: PublicKey; amount: bigint; reference: Buffer; ts: bigint; }
  export interface Recipe { version: number; bump: number; id: number; terms: RecipeTerms; effectiveAt: bigint; pending: RecipeTerms | null; pendingAt: bigint; uses: bigint; }
  export interface RecipeInput { materialId: number; amount: bigint; }
  export interface RecipeProposed { id: number; readyAt: bigint; }
  export interface RecipeTerms { kind: number; inputs: (RecipeInput)[]; feeLamports: bigint; templateId: number; paramMin: (number)[]; paramMax: (number)[]; chargesRestored: number; minLevel: number; active: boolean; }
  export interface Repaired { recipe: number; item: PublicKey; holder: PublicKey; restored: number; used: number; fee: bigint; reference: Buffer; ts: bigint; }
  export interface Wear { version: number; bump: number; item: PublicKey; maxCharges: number; used: number; dormant: boolean; repairs: number; updatedAt: bigint; }
  export interface WearOpened { item: PublicKey; maxCharges: number; ts: bigint; }
}

export namespace Book {
  export interface BookConfig { version: number; bump: number; admin: PublicKey; treasury: PublicKey; params: BookParams; protocolFeesTotal: bigint; markets: number; reserved: Buffer; }
  export interface BookEscrow { bump: number; market: PublicKey; }
  export interface BookMarket { version: number; bump: number; escrowBump: number; baseMint: PublicKey; materialId: number; tickLamports: bigint; minSize: bigint; seq: bigint; bids: (Order)[]; asks: (Order)[]; createdBy: PublicKey; fills: bigint; }
  export interface BookParams { takerBps: number; makerBps: number; slots: number; matchMax: number; createLevel: number; orderBountyLamports: bigint; adminTimelockSecs: number; }
  export interface BookParamsProposed { readyAt: bigint; }
  export interface Cancelled { market: PublicKey; id: bigint; owner: PublicKey; ts: bigint; }
  export interface ClassBid { version: number; bump: number; bidder: PublicKey; nonce: bigint; class: ClassKey; price: bigint; makerFee: bigint; expiresAt: bigint; createdAt: bigint; }
  export interface ClassBidCancelled { bid: PublicKey; ts: bigint; }
  export interface ClassBidPlaced { bid: PublicKey; bidder: PublicKey; templateId: number; minLevel: number; price: bigint; expiresAt: bigint; ts: bigint; }
  export interface ClassFilled { bid: PublicKey; item: PublicKey; seller: PublicKey; bidder: PublicKey; price: bigint; takerFee: bigint; makerFee: bigint; reference: Buffer; ts: bigint; }
  export interface ClassKey { templateId: number; minLevel: number; paramMin: (number)[]; paramMax: (number)[]; }
  export interface Evicted { market: PublicKey; id: bigint; owner: PublicKey; ts: bigint; }
  export interface Expired { market: PublicKey; id: bigint; owner: PublicKey; cranker: PublicKey; bounty: bigint; ts: bigint; }
  export interface Filled { market: PublicKey; makerOrder: bigint; maker: PublicKey; taker: PublicKey; side: number; price: bigint; size: bigint; takerFee: bigint; makerFee: bigint; reference: Buffer; ts: bigint; }
  export interface MarketCreated { market: PublicKey; baseMint: PublicKey; tickLamports: bigint; minSize: bigint; createdBy: PublicKey; ts: bigint; }
  export interface Order { id: bigint; owner: PublicKey; price: bigint; size: bigint; quoteLocked: bigint; bounty: bigint; expiresAt: bigint; }
  export interface PendingBook { bump: number; treasury: PublicKey; params: BookParams; readyAt: bigint; active: boolean; }
  export interface Placed { market: PublicKey; id: bigint; owner: PublicKey; side: number; price: bigint; size: bigint; resting: bigint; reference: Buffer; ts: bigint; }
  export interface ProtocolFee { source: number; mint: PublicKey; amount: bigint; reference: Buffer; ts: bigint; }
}
